// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:zenoh/src/bindings.dart')
library;

import 'dart:ffi' as ffi;

/// Initializes the Dart native API for dynamic linking.
///
/// Must be called before any other zenoh_dart functions that use
/// Dart native ports. Pass `NativeApi.initializeApiDLData` from Dart.
///
/// Returns 0 on success.
@ffi.Native<ffi.IntPtr Function(ffi.Pointer<ffi.Void>)>()
external int zd_init_dart_api_dl(ffi.Pointer<ffi.Void> data);

/// Initializes the zenoh logger from the RUST_LOG environment variable,
/// falling back to the provided filter string if RUST_LOG is not set.
///
/// @param fallback_filter  Filter string (e.g., "error", "info", "debug").
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>()
external void zd_init_log(ffi.Pointer<ffi.Char> fallback_filter);

/// Returns the size of z_owned_config_t in bytes.
///
/// Used by Dart to allocate the correct amount of native memory
/// for opaque zenoh types.
@ffi.Native<ffi.Size Function()>()
external int zd_config_sizeof();

/// Creates a default configuration.
///
/// @param config  Pointer to an uninitialized z_owned_config_t.
/// @return 0 on success, negative on failure.
@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Opaque>)>()
external int zd_config_default(ffi.Pointer<ffi.Opaque> config);

/// Inserts a JSON5 value into the configuration at the given key path.
///
/// Takes a mutable owned config pointer. Internally obtains a mutable loan
/// via z_config_loan_mut() before calling zc_config_insert_json5().
///
/// @param config  Pointer to a valid z_owned_config_t.
/// @param key     Configuration key path (e.g., "mode").
/// @param value   JSON5 value string (e.g., "\"peer\"").
/// @return 0 on success, negative on failure.
@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Opaque>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
  )
>()
external int zd_config_insert_json5(
  ffi.Pointer<ffi.Opaque> config,
  ffi.Pointer<ffi.Char> key,
  ffi.Pointer<ffi.Char> value,
);

/// Obtains a const loaned reference to the configuration.
///
/// @param config  Pointer to a valid z_owned_config_t.
/// @return Const pointer to the loaned config.
@ffi.Native<ffi.Pointer<ffi.Opaque> Function(ffi.Pointer<ffi.Opaque>)>()
external ffi.Pointer<ffi.Opaque> zd_config_loan(ffi.Pointer<ffi.Opaque> config);

/// Drops (frees) the configuration.
///
/// After this call the owned config is in gravestone state.
/// A second drop is a safe no-op.
///
/// @param config  Pointer to a z_owned_config_t to drop.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Opaque>)>()
external void zd_config_drop(ffi.Pointer<ffi.Opaque> config);

/// Returns the size of z_owned_session_t in bytes.
///
/// Used by Dart to allocate the correct amount of native memory
/// for opaque zenoh types.
@ffi.Native<ffi.Size Function()>()
external int zd_session_sizeof();

/// Opens a Zenoh session with the given configuration.
///
/// @param session  Pointer to an uninitialized z_owned_session_t.
/// @param config   Pointer to a z_owned_config_t (consumed by z_open).
/// @return 0 on success, negative on failure.
@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>)
>()
external int zd_open_session(
  ffi.Pointer<ffi.Opaque> session,
  ffi.Pointer<ffi.Opaque> config,
);

/// Obtains a const loaned reference to the session.
///
/// @param session  Pointer to a valid z_owned_session_t.
/// @return Const pointer to the loaned session.
@ffi.Native<ffi.Pointer<ffi.Opaque> Function(ffi.Pointer<ffi.Opaque>)>()
external ffi.Pointer<ffi.Opaque> zd_session_loan(
  ffi.Pointer<ffi.Opaque> session,
);

/// Gracefully closes and drops the session.
///
/// Calls z_close for graceful shutdown, then z_session_drop to release
/// resources. After this call the owned session is in gravestone state.
///
/// @param session  Pointer to a z_owned_session_t to close and drop.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Opaque>)>()
external void zd_close_session(ffi.Pointer<ffi.Opaque> session);

/// Returns the size of z_view_keyexpr_t in bytes.
///
/// Used by Dart to allocate the correct amount of native memory
/// for opaque zenoh types.
@ffi.Native<ffi.Size Function()>()
external int zd_view_keyexpr_sizeof();

/// Creates a view key expression from a null-terminated string.
///
/// The string must remain valid for the lifetime of the view.
///
/// @param ke    Pointer to an uninitialized z_view_keyexpr_t.
/// @param expr  Null-terminated key expression string.
/// @return 0 on success, Z_EINVAL (-1) if the expression is invalid.
@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Char>)>()
external int zd_view_keyexpr_from_str(
  ffi.Pointer<ffi.Opaque> ke,
  ffi.Pointer<ffi.Char> expr,
);

/// Obtains a const loaned reference to the key expression.
///
/// @param ke  Pointer to a valid z_view_keyexpr_t.
/// @return Const pointer to the loaned key expression.
@ffi.Native<ffi.Pointer<ffi.Opaque> Function(ffi.Pointer<ffi.Opaque>)>()
external ffi.Pointer<ffi.Opaque> zd_view_keyexpr_loan(
  ffi.Pointer<ffi.Opaque> ke,
);

/// Converts a loaned key expression to a view string.
///
/// The output view string borrows from the key expression and must not
/// outlive it. Returns void -- always succeeds on a valid loaned keyexpr.
///
/// @param ke   Const pointer to a loaned key expression.
/// @param out  Pointer to an uninitialized z_view_string_t to receive the result.
@ffi.Native<
  ffi.Void Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>)
>()
external void zd_keyexpr_as_view_string(
  ffi.Pointer<ffi.Opaque> ke,
  ffi.Pointer<ffi.Opaque> out,
);

/// Returns the size of z_owned_bytes_t in bytes.
///
/// Used by Dart to allocate the correct amount of native memory
/// for opaque zenoh types.
@ffi.Native<ffi.Size Function()>()
external int zd_bytes_sizeof();

/// Copies a null-terminated string into owned bytes.
///
/// @param bytes  Pointer to an uninitialized z_owned_bytes_t.
/// @param str    Null-terminated string to copy.
/// @return 0 on success, negative on failure.
@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Char>)>()
external int zd_bytes_copy_from_str(
  ffi.Pointer<ffi.Opaque> bytes,
  ffi.Pointer<ffi.Char> str,
);

/// Copies a buffer into owned bytes.
///
/// @param bytes  Pointer to an uninitialized z_owned_bytes_t.
/// @param data   Pointer to the buffer data.
/// @param len    Length of the buffer in bytes.
/// @return 0 on success, negative on failure.
@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Uint8>, ffi.Size)
>()
external int zd_bytes_copy_from_buf(
  ffi.Pointer<ffi.Opaque> bytes,
  ffi.Pointer<ffi.Uint8> data,
  int len,
);

/// Converts loaned bytes to an owned string.
///
/// @param bytes  Const pointer to a loaned bytes reference.
/// @param out    Pointer to an uninitialized z_owned_string_t to receive the result.
/// @return 0 on success, negative on failure.
@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>)
>()
external int zd_bytes_to_string(
  ffi.Pointer<ffi.Opaque> bytes,
  ffi.Pointer<ffi.Opaque> out,
);

/// Obtains a const loaned reference to the bytes.
///
/// @param bytes  Pointer to a valid z_owned_bytes_t.
/// @return Const pointer to the loaned bytes.
@ffi.Native<ffi.Pointer<ffi.Opaque> Function(ffi.Pointer<ffi.Opaque>)>()
external ffi.Pointer<ffi.Opaque> zd_bytes_loan(ffi.Pointer<ffi.Opaque> bytes);

/// Drops (frees) owned bytes.
///
/// After this call the owned bytes are in gravestone state.
/// A second drop is a safe no-op.
///
/// @param bytes  Pointer to a z_owned_bytes_t to drop.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Opaque>)>()
external void zd_bytes_drop(ffi.Pointer<ffi.Opaque> bytes);

/// Returns the size of z_owned_string_t in bytes.
///
/// Used by Dart to allocate the correct amount of native memory
/// for opaque zenoh types.
@ffi.Native<ffi.Size Function()>()
external int zd_string_sizeof();

/// Obtains a const loaned reference to the owned string.
///
/// @param str  Pointer to a valid z_owned_string_t.
/// @return Const pointer to the loaned string.
@ffi.Native<ffi.Pointer<ffi.Opaque> Function(ffi.Pointer<ffi.Opaque>)>()
external ffi.Pointer<ffi.Opaque> zd_string_loan(ffi.Pointer<ffi.Opaque> str);

/// Returns a pointer to the data of a loaned string.
///
/// The returned pointer is NOT guaranteed to be null-terminated.
///
/// @param str  Const pointer to a loaned string.
/// @return Pointer to the string data.
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Opaque>)>()
external ffi.Pointer<ffi.Char> zd_string_data(ffi.Pointer<ffi.Opaque> str);

/// Returns the length of a loaned string (in bytes, NOT including any terminator).
///
/// @param str  Const pointer to a loaned string.
/// @return Length of the string data in bytes.
@ffi.Native<ffi.Size Function(ffi.Pointer<ffi.Opaque>)>()
external int zd_string_len(ffi.Pointer<ffi.Opaque> str);

/// Drops (frees) an owned string.
///
/// After this call the owned string is in gravestone state.
/// A second drop is a safe no-op.
///
/// @param str  Pointer to a z_owned_string_t to drop.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Opaque>)>()
external void zd_string_drop(ffi.Pointer<ffi.Opaque> str);

/// Returns the size of z_view_string_t in bytes.
///
/// Used by Dart to allocate the correct amount of native memory
/// for opaque zenoh types.
@ffi.Native<ffi.Size Function()>()
external int zd_view_string_sizeof();

/// Returns a pointer to the data of a view string.
///
/// Internally loans the view string and calls z_string_data on the loaned ref.
/// The returned pointer is NOT guaranteed to be null-terminated.
///
/// @param str  Pointer to a valid z_view_string_t.
/// @return Pointer to the string data.
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Opaque>)>()
external ffi.Pointer<ffi.Char> zd_view_string_data(ffi.Pointer<ffi.Opaque> str);

/// Returns the length of a view string (in bytes, NOT including any terminator).
///
/// Internally loans the view string and calls z_string_len on the loaned ref.
///
/// @param str  Pointer to a valid z_view_string_t.
/// @return Length of the string data in bytes.
@ffi.Native<ffi.Size Function(ffi.Pointer<ffi.Opaque>)>()
external int zd_view_string_len(ffi.Pointer<ffi.Opaque> str);

/// Publishes data on the given key expression.
///
/// The payload is consumed (moved) by this call -- the caller must not
/// use the owned bytes after calling zd_put.
///
/// @param session  Const pointer to a loaned session.
/// @param keyexpr  Const pointer to a loaned key expression.
/// @param payload  Pointer to an owned bytes (consumed via z_bytes_move).
/// @return 0 on success, negative on failure.
@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Opaque>,
    ffi.Pointer<ffi.Opaque>,
    ffi.Pointer<ffi.Opaque>,
  )
>()
external int zd_put(
  ffi.Pointer<ffi.Opaque> session,
  ffi.Pointer<ffi.Opaque> keyexpr,
  ffi.Pointer<ffi.Opaque> payload,
);

/// Deletes a resource on the given key expression.
///
/// @param session  Const pointer to a loaned session.
/// @param keyexpr  Const pointer to a loaned key expression.
/// @return 0 on success, negative on failure.
@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>)
>()
external int zd_delete(
  ffi.Pointer<ffi.Opaque> session,
  ffi.Pointer<ffi.Opaque> keyexpr,
);

/// Returns the size of z_owned_subscriber_t in bytes.
///
/// Used by Dart to allocate the correct amount of native memory
/// for opaque zenoh types.
@ffi.Native<ffi.Size Function()>()
external int zd_subscriber_sizeof();

/// Declares a subscriber on the given key expression.
///
/// Samples are posted to the Dart isolate via `Dart_PostCObject_DL` on
/// the given native port. Each sample is sent as a `Dart_CObject` array
/// of 4 elements: [keyexpr(string), payload(Uint8List), kind(int64),
/// attachment(null or Uint8List)].
///
/// @param session     Const pointer to a loaned session.
/// @param subscriber  Pointer to an uninitialized z_owned_subscriber_t.
/// @param keyexpr     Const pointer to a loaned key expression.
/// @param dart_port   The Dart native port to post samples to.
/// @return 0 on success, negative on failure.
@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Opaque>,
    ffi.Pointer<ffi.Opaque>,
    ffi.Pointer<ffi.Opaque>,
    ffi.Int64,
  )
>()
external int zd_declare_subscriber(
  ffi.Pointer<ffi.Opaque> session,
  ffi.Pointer<ffi.Opaque> subscriber,
  ffi.Pointer<ffi.Opaque> keyexpr,
  int dart_port,
);

/// Drops (undeclares and frees) a subscriber.
///
/// After this call the owned subscriber is in gravestone state.
/// A second drop is a safe no-op.
///
/// @param subscriber  Pointer to a z_owned_subscriber_t to drop.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Opaque>)>()
external void zd_subscriber_drop(ffi.Pointer<ffi.Opaque> subscriber);

/// Returns the size of z_owned_publisher_t in bytes.
@ffi.Native<ffi.Size Function()>()
external int zd_publisher_sizeof();

/// Declares a publisher on the given key expression.
///
/// @param session             Const pointer to a loaned session.
/// @param publisher           Pointer to an uninitialized z_owned_publisher_t.
/// @param keyexpr             Const pointer to a loaned key expression.
/// @param encoding            MIME type string for default encoding (NULL = default).
/// @param congestion_control  Congestion control strategy (-1 = default/block).
/// @param priority            Message priority (-1 = default/data=5).
/// @return 0 on success, negative on failure.
@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Opaque>,
    ffi.Pointer<ffi.Opaque>,
    ffi.Pointer<ffi.Opaque>,
    ffi.Pointer<ffi.Char>,
    ffi.Int,
    ffi.Int,
  )
>()
external int zd_declare_publisher(
  ffi.Pointer<ffi.Opaque> session,
  ffi.Pointer<ffi.Opaque> publisher,
  ffi.Pointer<ffi.Opaque> keyexpr,
  ffi.Pointer<ffi.Char> encoding,
  int congestion_control,
  int priority,
);

/// Obtains a const loaned reference to the publisher.
@ffi.Native<ffi.Pointer<ffi.Opaque> Function(ffi.Pointer<ffi.Opaque>)>()
external ffi.Pointer<ffi.Opaque> zd_publisher_loan(
  ffi.Pointer<ffi.Opaque> publisher,
);

/// Drops (undeclares and frees) a publisher.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Opaque>)>()
external void zd_publisher_drop(ffi.Pointer<ffi.Opaque> publisher);

/// Publishes data through the publisher.
///
/// @param publisher   Const pointer to a loaned publisher.
/// @param payload     Pointer to owned bytes (consumed via z_bytes_move).
/// @param encoding    MIME type string for per-put encoding override (NULL = publisher default).
/// @param attachment  Pointer to owned bytes for attachment (consumed if non-NULL, NULL = no attachment).
/// @return 0 on success, negative on failure.
@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Opaque>,
    ffi.Pointer<ffi.Opaque>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Opaque>,
  )
>()
external int zd_publisher_put(
  ffi.Pointer<ffi.Opaque> publisher,
  ffi.Pointer<ffi.Opaque> payload,
  ffi.Pointer<ffi.Char> encoding,
  ffi.Pointer<ffi.Opaque> attachment,
);

/// Sends a DELETE through the publisher.
@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Opaque>)>()
external int zd_publisher_delete(ffi.Pointer<ffi.Opaque> publisher);

/// Returns the key expression of a publisher.
@ffi.Native<ffi.Pointer<ffi.Opaque> Function(ffi.Pointer<ffi.Opaque>)>()
external ffi.Pointer<ffi.Opaque> zd_publisher_keyexpr(
  ffi.Pointer<ffi.Opaque> publisher,
);

/// Declares a background matching listener on the publisher.
///
/// Matching status changes are posted to the Dart isolate via the given
/// native port as Int64 values (1 = matching, 0 = not matching).
///
/// @param publisher  Const pointer to a loaned publisher.
/// @param dart_port  The Dart native port to post matching status to.
/// @return 0 on success, negative on failure.
@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Opaque>, ffi.Int64)>()
external int zd_publisher_declare_background_matching_listener(
  ffi.Pointer<ffi.Opaque> publisher,
  int dart_port,
);

/// Gets the current matching status of a publisher.
///
/// @param publisher  Const pointer to a loaned publisher.
/// @param matching   Out parameter: filled with 0 (no match) or 1 (match).
/// @return 0 on success, negative on failure.
@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Int>)>()
external int zd_publisher_get_matching_status(
  ffi.Pointer<ffi.Opaque> publisher,
  ffi.Pointer<ffi.Int> matching,
);

/// Copies the session's own ZID (16 bytes) into the provided buffer.
///
/// @param session  Const pointer to a loaned session.
/// @param out_id   Pointer to a 16-byte buffer to receive the ZID.
@ffi.Native<
  ffi.Void Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Uint8>)
>()
external void zd_info_zid(
  ffi.Pointer<ffi.Opaque> session,
  ffi.Pointer<ffi.Uint8> out_id,
);

/// Converts a 16-byte ZID to its string representation.
///
/// @param id   Pointer to a 16-byte ZID buffer.
/// @param out  Pointer to an uninitialized z_owned_string_t to receive the result.
@ffi.Native<
  ffi.Void Function(ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Opaque>)
>()
external void zd_id_to_string(
  ffi.Pointer<ffi.Uint8> id,
  ffi.Pointer<ffi.Opaque> out,
);

/// Collects connected router ZIDs into a caller-provided buffer.
///
/// Each ZID is 16 bytes. The buffer must be at least max_count * 16 bytes.
///
/// @param session    Const pointer to a loaned session.
/// @param out_ids    Pointer to a buffer for ZID bytes (16 bytes per ZID).
/// @param max_count  Maximum number of ZIDs to collect.
/// @return Number of ZIDs written to the buffer.
@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Uint8>, ffi.Int)
>()
external int zd_info_routers_zid(
  ffi.Pointer<ffi.Opaque> session,
  ffi.Pointer<ffi.Uint8> out_ids,
  int max_count,
);

/// Collects connected peer ZIDs into a caller-provided buffer.
///
/// Each ZID is 16 bytes. The buffer must be at least max_count * 16 bytes.
///
/// @param session    Const pointer to a loaned session.
/// @param out_ids    Pointer to a buffer for ZID bytes (16 bytes per ZID).
/// @param max_count  Maximum number of ZIDs to collect.
/// @return Number of ZIDs written to the buffer.
@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Uint8>, ffi.Int)
>()
external int zd_info_peers_zid(
  ffi.Pointer<ffi.Opaque> session,
  ffi.Pointer<ffi.Uint8> out_ids,
  int max_count,
);

/// Scouts for zenoh entities on the network.
///
/// Each discovered hello is posted to the Dart native port as a
/// Dart_CObject array of 3 elements:
/// [0] TypedData(Uint8, 16 bytes) -- ZID
/// [1] Int64 -- whatami value
/// [2] String -- locators joined with ';'
///
/// After z_scout returns, a null sentinel is posted to signal completion.
///
/// @param config      Pointer to an owned config (consumed). NULL = default config.
/// @param dart_port   The Dart native port to post Hello messages to.
/// @param timeout_ms  Scouting timeout in milliseconds.
/// @param what        Bitmask of entity types to scout for (e.g., 3 = router+peer).
/// @return 0 on success, negative on failure.
@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Opaque>, ffi.Int64, ffi.Uint64, ffi.Int)
>()
external int zd_scout(
  ffi.Pointer<ffi.Opaque> config,
  int dart_port,
  int timeout_ms,
  int what,
);

/// Converts a whatami integer to a human-readable view string.
///
/// @param whatami  The whatami value (1=router, 2=peer, 4=client).
/// @param out      Pointer to an uninitialized z_view_string_t.
/// @return 0 on success, negative on failure.
@ffi.Native<ffi.Int Function(ffi.Int, ffi.Pointer<ffi.Opaque>)>()
external int zd_whatami_to_view_string(
  int whatami,
  ffi.Pointer<ffi.Opaque> out,
);

/// Returns the size of z_owned_shm_provider_t in bytes.
@ffi.Native<ffi.Size Function()>()
external int zd_shm_provider_sizeof();

/// Creates a default SHM provider with the given total size.
///
/// @param provider  Pointer to an uninitialized z_owned_shm_provider_t.
/// @param total_size  Total size of the SHM pool in bytes.
/// @return 0 on success, negative on failure.
@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Opaque>, ffi.Size)>()
external int zd_shm_provider_new(
  ffi.Pointer<ffi.Opaque> provider,
  int total_size,
);

/// Obtains a const loaned reference to the SHM provider.
@ffi.Native<ffi.Pointer<ffi.Opaque> Function(ffi.Pointer<ffi.Opaque>)>()
external ffi.Pointer<ffi.Opaque> zd_shm_provider_loan(
  ffi.Pointer<ffi.Opaque> provider,
);

/// Drops (frees) the SHM provider.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Opaque>)>()
external void zd_shm_provider_drop(ffi.Pointer<ffi.Opaque> provider);

/// Returns the available (free) bytes in the SHM provider.
@ffi.Native<ffi.Size Function(ffi.Pointer<ffi.Opaque>)>()
external int zd_shm_provider_available(ffi.Pointer<ffi.Opaque> provider);

/// Returns the size of z_owned_shm_mut_t in bytes.
@ffi.Native<ffi.Size Function()>()
external int zd_shm_mut_sizeof();

/// Allocates a mutable SHM buffer from the provider.
///
/// @param provider  Const pointer to a loaned SHM provider.
/// @param buf       Pointer to an uninitialized z_owned_shm_mut_t.
/// @param size      Size of the buffer to allocate.
/// @return 0 on success, negative on failure.
@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>, ffi.Size)
>()
external int zd_shm_provider_alloc(
  ffi.Pointer<ffi.Opaque> provider,
  ffi.Pointer<ffi.Opaque> buf,
  int size,
);

/// Allocates a mutable SHM buffer with GC + defrag + blocking.
///
/// @param provider  Const pointer to a loaned SHM provider.
/// @param buf       Pointer to an uninitialized z_owned_shm_mut_t.
/// @param size      Size of the buffer to allocate.
/// @return 0 on success, negative on failure.
@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>, ffi.Size)
>()
external int zd_shm_provider_alloc_gc_defrag_blocking(
  ffi.Pointer<ffi.Opaque> provider,
  ffi.Pointer<ffi.Opaque> buf,
  int size,
);

/// Obtains a mutable loaned reference to the SHM buffer.
@ffi.Native<ffi.Pointer<ffi.Opaque> Function(ffi.Pointer<ffi.Opaque>)>()
external ffi.Pointer<ffi.Opaque> zd_shm_mut_loan_mut(
  ffi.Pointer<ffi.Opaque> buf,
);

/// Returns a mutable pointer to the SHM buffer data.
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.Pointer<ffi.Opaque>)>()
external ffi.Pointer<ffi.Uint8> zd_shm_mut_data_mut(
  ffi.Pointer<ffi.Opaque> buf,
);

/// Returns the length of the SHM buffer.
@ffi.Native<ffi.Size Function(ffi.Pointer<ffi.Opaque>)>()
external int zd_shm_mut_len(ffi.Pointer<ffi.Opaque> buf);

/// Converts a mutable SHM buffer into owned bytes (consuming the buffer).
///
/// @param bytes  Pointer to an uninitialized z_owned_bytes_t.
/// @param buf    Pointer to a z_owned_shm_mut_t (consumed).
/// @return 0 on success, negative on failure.
@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>)
>()
external int zd_bytes_from_shm_mut(
  ffi.Pointer<ffi.Opaque> bytes,
  ffi.Pointer<ffi.Opaque> buf,
);

/// Drops (frees) a mutable SHM buffer.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Opaque>)>()
external void zd_shm_mut_drop(ffi.Pointer<ffi.Opaque> buf);

final class UnnamedStruct extends ffi.Struct {
  @ffi.UnsignedInt()
  external int __low;

  @ffi.UnsignedInt()
  external int __high;
}

final class __atomic_wide_counter extends ffi.Union {
  @ffi.UnsignedLongLong()
  external int __value64;

  external UnnamedStruct __value32;
}

final class __pthread_internal_list extends ffi.Struct {
  external ffi.Pointer<__pthread_internal_list> __prev;

  external ffi.Pointer<__pthread_internal_list> __next;
}

final class __pthread_mutex_s extends ffi.Struct {
  @ffi.Int()
  external int __lock;

  @ffi.UnsignedInt()
  external int __count;

  @ffi.Int()
  external int __owner;

  @ffi.UnsignedInt()
  external int __nusers;

  @ffi.Int()
  external int __kind;

  @ffi.Short()
  external int __spins;

  @ffi.Short()
  external int __elision;

  external __pthread_internal_list __list;
}

final class __pthread_rwlock_arch_t extends ffi.Struct {
  @ffi.UnsignedInt()
  external int __readers;

  @ffi.UnsignedInt()
  external int __writers;

  @ffi.UnsignedInt()
  external int __wrphase_futex;

  @ffi.UnsignedInt()
  external int __writers_futex;

  @ffi.UnsignedInt()
  external int __pad3;

  @ffi.UnsignedInt()
  external int __pad4;

  @ffi.Int()
  external int __cur_writer;

  @ffi.Int()
  external int __shared;

  @ffi.SignedChar()
  external int __rwelision;

  @ffi.Array.multi([7])
  external ffi.Array<ffi.UnsignedChar> __pad1;

  @ffi.UnsignedLong()
  external int __pad2;

  @ffi.UnsignedInt()
  external int __flags;
}

final class __pthread_cond_s extends ffi.Struct {
  external __atomic_wide_counter __wseq;

  external __atomic_wide_counter __g1_start;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.UnsignedInt> __g_refs;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.UnsignedInt> __g_size;

  @ffi.UnsignedInt()
  external int __g1_orig_size;

  @ffi.UnsignedInt()
  external int __wrefs;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.UnsignedInt> __g_signals;
}

final class pthread_mutexattr_t extends ffi.Union {
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Char> __size;

  @ffi.Int()
  external int __align;
}

final class pthread_condattr_t extends ffi.Union {
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Char> __size;

  @ffi.Int()
  external int __align;
}

final class pthread_attr_t extends ffi.Union {
  @ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_mutex_t extends ffi.Union {
  external __pthread_mutex_s __data;

  @ffi.Array.multi([40])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_cond_t extends ffi.Union {
  external __pthread_cond_s __data;

  @ffi.Array.multi([48])
  external ffi.Array<ffi.Char> __size;

  @ffi.LongLong()
  external int __align;
}

final class pthread_rwlock_t extends ffi.Union {
  external __pthread_rwlock_arch_t __data;

  @ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_rwlockattr_t extends ffi.Union {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_barrier_t extends ffi.Union {
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_barrierattr_t extends ffi.Union {
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Char> __size;

  @ffi.Int()
  external int __align;
}

/// @warning This API has been marked as unstable: it works as advertised, but it may be changed in a future release.
/// @brief An owned ZShmMut slice.
final class z_owned_shm_mut_t extends ffi.Struct {
  @ffi.Array.multi([80])
  external ffi.Array<ffi.Uint8> _0;
}

/// @warning This API has been marked as unstable: it works as advertised, but it may be changed in a future release.
/// @brief A loaned ShmProvider's PrecomputedLayout.
final class z_loaned_precomputed_layout_t extends ffi.Struct {
  @ffi.Array.multi([40])
  external ffi.Array<ffi.Uint8> _0;
}

/// @warning This API has been marked as unstable: it works as advertised, but it may be changed in a future release.
/// @brief An owned ShmProvider's PrecomputedLayout.
final class z_owned_precomputed_layout_t extends ffi.Struct {
  @ffi.Array.multi([40])
  external ffi.Array<ffi.Uint8> _0;
}

/// @warning This API has been marked as unstable: it works as advertised, but it may be changed in a future release.
/// @brief A loaned ShmProvider.
final class z_loaned_shm_provider_t extends ffi.Struct {
  @ffi.Array.multi([104])
  external ffi.Array<ffi.Uint8> _0;
}

/// A loaned Zenoh data.
final class z_loaned_bytes_t extends ffi.Struct {
  @ffi.Array.multi([40])
  external ffi.Array<ffi.Uint8> _0;
}

/// @warning This API has been marked as unstable: it works as advertised, but it may be changed in a future release.
/// @brief A loaned ZShm slice.
final class z_loaned_shm_t extends ffi.Struct {
  @ffi.Array.multi([80])
  external ffi.Array<ffi.Uint8> _0;
}

/// A Zenoh data.
///
/// To minimize copies and reallocations, Zenoh may provide data in several separate buffers.
final class z_owned_bytes_t extends ffi.Struct {
  @ffi.Array.multi([40])
  external ffi.Array<ffi.Uint8> _0;
}

/// A loaned sequence of bytes.
final class z_loaned_slice_t extends ffi.Struct {
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Uint8> _0;
}

/// A loaned string.
final class z_loaned_string_t extends ffi.Struct {
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Uint8> _0;
}

/// @warning This API has been marked as unstable: it works as advertised, but it may be changed in a future release.
/// @brief An owned ZShm slice.
final class z_owned_shm_t extends ffi.Struct {
  @ffi.Array.multi([80])
  external ffi.Array<ffi.Uint8> _0;
}

final class z_owned_slice_t extends ffi.Struct {
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Uint8> _0;
}

/// The wrapper type for strings allocated by Zenoh.
final class z_owned_string_t extends ffi.Struct {
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Uint8> _0;
}

/// A contiguous sequence of bytes owned by some other entity.
final class z_view_slice_t extends ffi.Struct {
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Uint8> _0;
}

/// An loaned writer for payload.
final class z_loaned_bytes_writer_t extends ffi.Struct {
  @ffi.Array.multi([64])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned writer for payload.
final class z_owned_bytes_writer_t extends ffi.Struct {
  @ffi.Array.multi([64])
  external ffi.Array<ffi.Uint8> _0;
}

/// @warning This API has been marked as unstable: it works as advertised, but it may be changed in a future release.
/// @brief A loaned cancellation token, which can be used to interrupt GET queries.
final class z_loaned_cancellation_token_t extends ffi.Struct {
  @ffi.Array.multi([24])
  external ffi.Array<ffi.Uint8> _0;
}

/// @warning This API has been marked as unstable: it works as advertised, but it may be changed in a future release.
/// @brief An owned cancellation token, which can be used to interrupt GET queries.
final class z_owned_cancellation_token_t extends ffi.Struct {
  @ffi.Array.multi([24])
  external ffi.Array<ffi.Uint8> _0;
}

/// @warning This API has been marked as unstable: it works as advertised, but it may be changed in a future release.
/// @brief An owned ChunkAllocResult.
final class z_owned_chunk_alloc_result_t extends ffi.Struct {
  @ffi.Array.multi([48])
  external ffi.Array<ffi.Uint8> _0;
}

/// @warning This API has been marked as unstable: it works as advertised, but it may be changed in a future release.
/// @brief A pointer in SHM Segment.
final class z_owned_ptr_in_segment_t extends ffi.Struct {
  @ffi.Array.multi([24])
  external ffi.Array<ffi.Uint8> _0;
}

/// A loaned Zenoh session.
final class z_loaned_session_t extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> _0;
}

/// A loaned hello message.
final class z_loaned_hello_t extends ffi.Struct {
  @ffi.Array.multi([48])
  external ffi.Array<ffi.Uint8> _0;
}

/// Loaned closure.
final class z_loaned_closure_hello_t extends ffi.Struct {
  @ffi.Size()
  external int _0;

  @ffi.Size()
  external int _1;

  @ffi.Size()
  external int _2;
}

/// @warning This API has been marked as unstable: it works as advertised, but it may be changed in a future release.
/// @brief Loaned closure.
final class z_loaned_closure_matching_status_t extends ffi.Struct {
  @ffi.Size()
  external int _0;

  @ffi.Size()
  external int _1;

  @ffi.Size()
  external int _2;
}

/// A loaned Zenoh query.
final class z_loaned_query_t extends ffi.Struct {
  @ffi.Array.multi([144])
  external ffi.Array<ffi.Uint8> _0;
}

/// Loaned closure.
final class z_loaned_closure_query_t extends ffi.Struct {
  @ffi.Size()
  external int _0;

  @ffi.Size()
  external int _1;

  @ffi.Size()
  external int _2;
}

/// A loaned reply.
final class z_loaned_reply_t extends ffi.Struct {
  @ffi.Array.multi([248])
  external ffi.Array<ffi.Uint8> _0;
}

/// Loaned closure.
final class z_loaned_closure_reply_t extends ffi.Struct {
  @ffi.Size()
  external int _0;

  @ffi.Size()
  external int _1;

  @ffi.Size()
  external int _2;
}

/// A loaned Zenoh sample.
final class z_loaned_sample_t extends ffi.Struct {
  @ffi.Array.multi([224])
  external ffi.Array<ffi.Uint8> _0;
}

/// Loaned closure.
final class z_loaned_closure_sample_t extends ffi.Struct {
  @ffi.Size()
  external int _0;

  @ffi.Size()
  external int _1;

  @ffi.Size()
  external int _2;
}

/// @brief A Zenoh ID.
///
/// In general, valid Zenoh IDs are LSB-first 128bit unsigned and non-zero integers.
final class z_id_t extends ffi.Struct {
  @ffi.Array.multi([16])
  external ffi.Array<ffi.Uint8> id;
}

/// @brief Loaned closure.
final class z_loaned_closure_zid_t extends ffi.Struct {
  @ffi.Size()
  external int _0;

  @ffi.Size()
  external int _1;

  @ffi.Size()
  external int _2;
}

/// An owned conditional variable.
///
/// Used in combination with `z_owned_mutex_t` to wake up thread when certain conditions are met.
final class z_owned_condvar_t extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> _0;
}

/// A loaned conditional variable.
final class z_loaned_condvar_t extends ffi.Struct {
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Uint8> _0;
}

/// A loaned mutex.
final class z_loaned_mutex_t extends ffi.Struct {
  @ffi.Array.multi([24])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned Zenoh configuration.
final class z_owned_config_t extends ffi.Struct {
  @ffi.Array.multi([2008])
  external ffi.Array<ffi.Uint8> _0;
}

/// A loaned Zenoh configuration.
final class z_loaned_config_t extends ffi.Struct {
  @ffi.Array.multi([2008])
  external ffi.Array<ffi.Uint8> _0;
}

/// A loaned key expression.
///
/// Key expressions can identify a single key or a set of keys.
///
/// Examples :
/// - ``"key/expression"``.
/// - ``"key/ex*"``.
///
/// Using `z_declare_keyexpr` allows Zenoh to optimize a key expression,
/// both for local processing and network-wise.
final class z_loaned_keyexpr_t extends ffi.Struct {
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Uint8> _0;
}

/// A Zenoh-allocated <a href="https://zenoh.io/docs/manual/abstractions/#key-expression"> key expression </a>.
///
/// Key expressions can identify a single key or a set of keys.
///
/// Examples :
/// - ``"key/expression"``.
/// - ``"key/ex*"``.
///
/// Key expressions can be mapped to numerical ids through `z_declare_keyexpr`
/// for wire and computation efficiency.
///
/// Internally key expressiobn can be either:
/// - A plain string expression.
/// - A pure numerical id.
/// - The combination of a numerical prefix and a string suffix.
final class z_owned_keyexpr_t extends ffi.Struct {
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned Zenoh <a href="https://zenoh.io/docs/manual/abstractions/#publisher"> publisher </a>.
final class z_owned_publisher_t extends ffi.Struct {
  @ffi.Array.multi([112])
  external ffi.Array<ffi.Uint8> _0;
}

/// The <a href="https://zenoh.io/docs/manual/abstractions/#encoding"> encoding </a> of Zenoh data.
final class z_owned_encoding_t extends ffi.Struct {
  @ffi.Array.multi([48])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned Zenoh querier.
///
/// Sends queries to matching queryables.
final class z_owned_querier_t extends ffi.Struct {
  @ffi.Array.multi([80])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned Zenoh <a href="https://zenoh.io/docs/manual/abstractions/#queryable"> queryable </a>.
///
/// Responds to queries sent via `z_get()` with intersecting key expression.
final class z_owned_queryable_t extends ffi.Struct {
  @ffi.Array.multi([48])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned Zenoh <a href="https://zenoh.io/docs/manual/abstractions/#subscriber"> subscriber </a>.
///
/// Receives data from publication on intersecting key expressions.
/// Destroying the subscriber cancels the subscription.
final class z_owned_subscriber_t extends ffi.Struct {
  @ffi.Array.multi([48])
  external ffi.Array<ffi.Uint8> _0;
}

/// A loaned Zenoh encoding.
final class z_loaned_encoding_t extends ffi.Struct {
  @ffi.Array.multi([48])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned Zenoh fifo query handler.
final class z_owned_fifo_handler_query_t extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned Zenoh fifo reply handler.
final class z_owned_fifo_handler_reply_t extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned Zenoh fifo sample handler.
final class z_owned_fifo_handler_sample_t extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> _0;
}

/// An loaned Zenoh fifo query handler.
final class z_loaned_fifo_handler_query_t extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned Zenoh query received by a queryable.
///
/// Queries are atomically reference-counted, letting you extract them from the callback that handed them to you by cloning.
final class z_owned_query_t extends ffi.Struct {
  @ffi.Array.multi([144])
  external ffi.Array<ffi.Uint8> _0;
}

/// An loaned Zenoh fifo reply handler.
final class z_loaned_fifo_handler_reply_t extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned reply from a Queryable to a `z_get()`.
final class z_owned_reply_t extends ffi.Struct {
  @ffi.Array.multi([248])
  external ffi.Array<ffi.Uint8> _0;
}

/// An loaned Zenoh fifo sample handler.
final class z_loaned_fifo_handler_sample_t extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned Zenoh sample.
///
/// This is a read only type that can only be constructed by cloning a `z_loaned_sample_t`.
/// Like all owned types, it should be freed using z_drop or z_sample_drop.
final class z_owned_sample_t extends ffi.Struct {
  @ffi.Array.multi([224])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned Zenoh-allocated hello message returned by a Zenoh entity to a scout message sent with `z_scout()`.
final class z_owned_hello_t extends ffi.Struct {
  @ffi.Array.multi([48])
  external ffi.Array<ffi.Uint8> _0;
}

/// An array of maybe-owned non-null terminated strings.
final class z_owned_string_array_t extends ffi.Struct {
  @ffi.Array.multi([24])
  external ffi.Array<ffi.Uint8> _0;
}

/// @brief A liveliness token that can be used to provide the network with information about connectivity to its
/// declarer: when constructed, a PUT sample will be received by liveliness subscribers on intersecting key
/// expressions.
///
/// A DELETE on the token's key expression will be received by subscribers if the token is destroyed, or if connectivity between the subscriber and the token's creator is lost.
final class z_owned_liveliness_token_t extends ffi.Struct {
  @ffi.Array.multi([16])
  external ffi.Array<ffi.Uint8> _0;
}

/// @brief An owned Zenoh matching listener.
///
/// A listener that sends notifications when the [`MatchingStatus`] of a publisher or querier changes.
/// Dropping the corresponding publisher, also drops matching listener.
final class z_owned_matching_listener_t extends ffi.Struct {
  @ffi.Array.multi([24])
  external ffi.Array<ffi.Uint8> _0;
}

/// @warning This API has been marked as unstable: it works as advertised, but it may be changed in a future release.
/// @brief An owned MemoryLayout.
final class z_owned_memory_layout_t extends ffi.Struct {
  @ffi.Array.multi([16])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned mutex.
final class z_owned_mutex_t extends ffi.Struct {
  @ffi.Array.multi([24])
  external ffi.Array<ffi.Uint8> _0;
}

/// A Zenoh reply error - a combination of reply error payload and its encoding.
final class z_owned_reply_err_t extends ffi.Struct {
  @ffi.Array.multi([88])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned Zenoh ring query handler.
final class z_owned_ring_handler_query_t extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned Zenoh ring reply handler.
final class z_owned_ring_handler_reply_t extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned Zenoh ring sample handler.
final class z_owned_ring_handler_sample_t extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned Zenoh session.
final class z_owned_session_t extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> _0;
}

/// @warning This API has been marked as unstable: it works as advertised, but it may be changed in a future release.
/// @brief An owned shared ShmProvider.
final class z_owned_shared_shm_provider_t extends ffi.Struct {
  @ffi.Array.multi([104])
  external ffi.Array<ffi.Uint8> _0;
}

/// @warning This API has been marked as unstable: it works as advertised, but it may be changed in a future release.
/// @brief An owned SHM Client.
final class z_owned_shm_client_t extends ffi.Struct {
  @ffi.Array.multi([16])
  external ffi.Array<ffi.Uint8> _0;
}

/// @warning This API has been marked as unstable: it works as advertised, but it may be changed in a future release.
/// @brief An owned SHM Client Storage
final class z_owned_shm_client_storage_t extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> _0;
}

/// @warning This API has been marked as unstable: it works as advertised, but it may be changed in a future release.
/// @brief An owned ShmProvider.
final class z_owned_shm_provider_t extends ffi.Struct {
  @ffi.Array.multi([104])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned Zenoh task.
final class z_owned_task_t extends ffi.Struct {
  @ffi.Array.multi([24])
  external ffi.Array<ffi.Uint8> _0;
}

/// The view over a string.
final class z_view_string_t extends ffi.Struct {
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Uint8> _0;
}

final class z_loaned_liveliness_token_t extends ffi.Struct {
  @ffi.Array.multi([16])
  external ffi.Array<ffi.Uint8> _0;
}

/// @warning This API has been marked as unstable: it works as advertised, but it may be changed in a future release.
/// @brief A loaned MemoryLayout.
final class z_loaned_memory_layout_t extends ffi.Struct {
  @ffi.Array.multi([16])
  external ffi.Array<ffi.Uint8> _0;
}

/// A loaned SHM Client Storage.
final class z_loaned_shm_client_storage_t extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> _0;
}

/// @warning This API has been marked as unstable: it works as advertised, but it may be changed in a future release.
/// @brief A loaned pointer in SHM Segment.
final class z_loaned_ptr_in_segment_t extends ffi.Struct {
  @ffi.Array.multi([24])
  external ffi.Array<ffi.Uint8> _0;
}

/// A loaned Zenoh publisher.
final class z_loaned_publisher_t extends ffi.Struct {
  @ffi.Array.multi([112])
  external ffi.Array<ffi.Uint8> _0;
}

/// A loaned Zenoh queryable.
final class z_loaned_querier_t extends ffi.Struct {
  @ffi.Array.multi([80])
  external ffi.Array<ffi.Uint8> _0;
}

/// A loaned Zenoh queryable.
final class z_loaned_queryable_t extends ffi.Struct {
  @ffi.Array.multi([48])
  external ffi.Array<ffi.Uint8> _0;
}

/// A loaned Zenoh reply error.
final class z_loaned_reply_err_t extends ffi.Struct {
  @ffi.Array.multi([88])
  external ffi.Array<ffi.Uint8> _0;
}

/// An loaned Zenoh ring query handler.
final class z_loaned_ring_handler_query_t extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> _0;
}

/// An loaned Zenoh ring reply handler.
final class z_loaned_ring_handler_reply_t extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> _0;
}

/// An loaned Zenoh ring sample handler.
final class z_loaned_ring_handler_sample_t extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> _0;
}

/// @warning This API has been marked as unstable: it works as advertised, but it may be changed in a future release.
/// @brief A loaned shared ShmProvider.
final class z_loaned_shared_shm_provider_t extends ffi.Struct {
  @ffi.Array.multi([104])
  external ffi.Array<ffi.Uint8> _0;
}

/// @warning This API has been marked as unstable: it works as advertised, but it may be changed in a future release.
/// @brief A loaned ZShmMut slice.
final class z_loaned_shm_mut_t extends ffi.Struct {
  @ffi.Array.multi([80])
  external ffi.Array<ffi.Uint8> _0;
}

/// A loaned string array.
final class z_loaned_string_array_t extends ffi.Struct {
  @ffi.Array.multi([24])
  external ffi.Array<ffi.Uint8> _0;
}

/// A loaned Zenoh subscriber.
final class z_loaned_subscriber_t extends ffi.Struct {
  @ffi.Array.multi([48])
  external ffi.Array<ffi.Uint8> _0;
}

/// A user allocated string, viewed as a key expression.
final class z_view_keyexpr_t extends ffi.Struct {
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Uint8> _0;
}

final class z_moved_precomputed_layout_t extends ffi.Struct {
  external z_owned_precomputed_layout_t _this;
}

final class z_moved_bytes_t extends ffi.Struct {
  external z_owned_bytes_t _this;
}

final class z_moved_shm_t extends ffi.Struct {
  external z_owned_shm_t _this;
}

final class z_moved_shm_mut_t extends ffi.Struct {
  external z_owned_shm_mut_t _this;
}

final class z_moved_slice_t extends ffi.Struct {
  external z_owned_slice_t _this;
}

final class z_moved_string_t extends ffi.Struct {
  external z_owned_string_t _this;
}

final class z_moved_bytes_writer_t extends ffi.Struct {
  external z_owned_bytes_writer_t _this;
}

final class z_moved_cancellation_token_t extends ffi.Struct {
  external z_owned_cancellation_token_t _this;
}

final class z_moved_chunk_alloc_result_t extends ffi.Struct {
  external z_owned_chunk_alloc_result_t _this;
}

final class z_moved_ptr_in_segment_t extends ffi.Struct {
  external z_owned_ptr_in_segment_t _this;
}

/// @brief A hello message-processing closure.
///
/// A closure is a structure that contains all the elements for stateful, memory-leak-free callbacks.
final class z_owned_closure_hello_t extends ffi.Struct {
  external ffi.Pointer<ffi.Void> _context;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<z_loaned_hello_t> hello,
        ffi.Pointer<ffi.Void> context,
      )
    >
  >
  _call;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> context)>
  >
  _drop;
}

/// Moved closure.
final class z_moved_closure_hello_t extends ffi.Struct {
  external z_owned_closure_hello_t _this;
}

/// @brief A struct that indicates if there exist Subscribers matching the Publisher's key expression or Queryables matching Querier's key expression and target.
final class z_matching_status_t extends ffi.Struct {
  /// True if there exist matching Zenoh entities, false otherwise.
  @ffi.Bool()
  external bool matching;
}

/// @warning This API has been marked as unstable: it works as advertised, but it may be changed in a future release.
/// @brief A matching status-processing closure.
///
/// A closure is a structure that contains all the elements for stateful, memory-leak-free callbacks.
final class z_owned_closure_matching_status_t extends ffi.Struct {
  external ffi.Pointer<ffi.Void> _context;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<z_matching_status_t> matching_status,
        ffi.Pointer<ffi.Void> context,
      )
    >
  >
  _call;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> context)>
  >
  _drop;
}

/// @warning This API has been marked as unstable: it works as advertised, but it may be changed in a future release.
/// @brief Moved closure.
final class z_moved_closure_matching_status_t extends ffi.Struct {
  external z_owned_closure_matching_status_t _this;
}

/// @brief A query-processing closure.
///
/// A closure is a structure that contains all the elements for stateful, memory-leak-free callbacks.
final class z_owned_closure_query_t extends ffi.Struct {
  external ffi.Pointer<ffi.Void> _context;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<z_loaned_query_t> query,
        ffi.Pointer<ffi.Void> context,
      )
    >
  >
  _call;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> context)>
  >
  _drop;
}

/// Moved closure.
final class z_moved_closure_query_t extends ffi.Struct {
  external z_owned_closure_query_t _this;
}

/// @brief A reply-processing closure.
///
/// A closure is a structure that contains all the elements for stateful, memory-leak-free callbacks.
final class z_owned_closure_reply_t extends ffi.Struct {
  external ffi.Pointer<ffi.Void> _context;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<z_loaned_reply_t> reply,
        ffi.Pointer<ffi.Void> context,
      )
    >
  >
  _call;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> context)>
  >
  _drop;
}

/// Moved closure.
final class z_moved_closure_reply_t extends ffi.Struct {
  external z_owned_closure_reply_t _this;
}

/// @brief A sample-processing closure.
///
/// A closure is a structure that contains all the elements for stateful, memory-leak-free callbacks.
final class z_owned_closure_sample_t extends ffi.Struct {
  external ffi.Pointer<ffi.Void> _context;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<z_loaned_sample_t> sample,
        ffi.Pointer<ffi.Void> context,
      )
    >
  >
  _call;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> context)>
  >
  _drop;
}

/// Moved closure.
final class z_moved_closure_sample_t extends ffi.Struct {
  external z_owned_closure_sample_t _this;
}

/// @brief A zenoh id-processing closure.
///
/// A closure is a structure that contains all the elements for stateful, memory-leak-free callbacks:
final class z_owned_closure_zid_t extends ffi.Struct {
  external ffi.Pointer<ffi.Void> _context;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<z_id_t> z_id, ffi.Pointer<ffi.Void> context)
    >
  >
  _call;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> context)>
  >
  _drop;
}

/// @brief Moved closure.
final class z_moved_closure_zid_t extends ffi.Struct {
  external z_owned_closure_zid_t _this;
}

final class z_moved_condvar_t extends ffi.Struct {
  external z_owned_condvar_t _this;
}

final class z_moved_config_t extends ffi.Struct {
  external z_owned_config_t _this;
}

final class z_moved_encoding_t extends ffi.Struct {
  external z_owned_encoding_t _this;
}

final class z_moved_fifo_handler_query_t extends ffi.Struct {
  external z_owned_fifo_handler_query_t _this;
}

final class z_moved_fifo_handler_reply_t extends ffi.Struct {
  external z_owned_fifo_handler_reply_t _this;
}

final class z_moved_fifo_handler_sample_t extends ffi.Struct {
  external z_owned_fifo_handler_sample_t _this;
}

final class z_moved_hello_t extends ffi.Struct {
  external z_owned_hello_t _this;
}

final class z_moved_keyexpr_t extends ffi.Struct {
  external z_owned_keyexpr_t _this;
}

final class z_moved_liveliness_token_t extends ffi.Struct {
  external z_owned_liveliness_token_t _this;
}

final class z_moved_matching_listener_t extends ffi.Struct {
  external z_owned_matching_listener_t _this;
}

final class z_moved_memory_layout_t extends ffi.Struct {
  external z_owned_memory_layout_t _this;
}

final class z_moved_mutex_t extends ffi.Struct {
  external z_owned_mutex_t _this;
}

final class z_moved_publisher_t extends ffi.Struct {
  external z_owned_publisher_t _this;
}

final class z_moved_querier_t extends ffi.Struct {
  external z_owned_querier_t _this;
}

final class z_moved_query_t extends ffi.Struct {
  external z_owned_query_t _this;
}

final class z_moved_queryable_t extends ffi.Struct {
  external z_owned_queryable_t _this;
}

final class z_moved_reply_t extends ffi.Struct {
  external z_owned_reply_t _this;
}

final class z_moved_reply_err_t extends ffi.Struct {
  external z_owned_reply_err_t _this;
}

final class z_moved_ring_handler_query_t extends ffi.Struct {
  external z_owned_ring_handler_query_t _this;
}

final class z_moved_ring_handler_reply_t extends ffi.Struct {
  external z_owned_ring_handler_reply_t _this;
}

final class z_moved_ring_handler_sample_t extends ffi.Struct {
  external z_owned_ring_handler_sample_t _this;
}

final class z_moved_sample_t extends ffi.Struct {
  external z_owned_sample_t _this;
}

final class z_moved_session_t extends ffi.Struct {
  external z_owned_session_t _this;
}

final class z_moved_shared_shm_provider_t extends ffi.Struct {
  external z_owned_shared_shm_provider_t _this;
}

final class z_moved_shm_client_t extends ffi.Struct {
  external z_owned_shm_client_t _this;
}

final class z_moved_shm_client_storage_t extends ffi.Struct {
  external z_owned_shm_client_storage_t _this;
}

final class z_moved_shm_provider_t extends ffi.Struct {
  external z_owned_shm_provider_t _this;
}

final class z_moved_string_array_t extends ffi.Struct {
  external z_owned_string_array_t _this;
}

final class z_moved_subscriber_t extends ffi.Struct {
  external z_owned_subscriber_t _this;
}

final class z_moved_task_t extends ffi.Struct {
  external z_owned_task_t _this;
}
