// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Auto-generated FFI bindings for zenoh_dart C shim.
class ZenohDartBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  ZenohDartBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  ZenohDartBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// Initializes the Dart native API for dynamic linking.
  ///
  /// Must be called before any other zenoh_dart functions that use
  /// Dart native ports. Pass `NativeApi.initializeApiDLData` from Dart.
  ///
  /// Returns 0 on success.
  int zd_init_dart_api_dl(ffi.Pointer<ffi.Void> data) {
    return _zd_init_dart_api_dl(data);
  }

  late final _zd_init_dart_api_dlPtr =
      _lookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.Pointer<ffi.Void>)>>(
        'zd_init_dart_api_dl',
      );
  late final _zd_init_dart_api_dl = _zd_init_dart_api_dlPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  /// Initializes the zenoh logger from the RUST_LOG environment variable,
  /// falling back to the provided filter string if RUST_LOG is not set.
  ///
  /// @param fallback_filter  Filter string (e.g., "error", "info", "debug").
  void zd_init_log(ffi.Pointer<ffi.Char> fallback_filter) {
    return _zd_init_log(fallback_filter);
  }

  late final _zd_init_logPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
        'zd_init_log',
      );
  late final _zd_init_log = _zd_init_logPtr
      .asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  /// Returns the size of z_owned_config_t in bytes.
  ///
  /// Used by Dart to allocate the correct amount of native memory
  /// for opaque zenoh types.
  int zd_config_sizeof() {
    return _zd_config_sizeof();
  }

  late final _zd_config_sizeofPtr =
      _lookup<ffi.NativeFunction<ffi.Size Function()>>('zd_config_sizeof');
  late final _zd_config_sizeof = _zd_config_sizeofPtr
      .asFunction<int Function()>();

  /// Creates a default configuration.
  ///
  /// @param config  Pointer to an uninitialized z_owned_config_t.
  /// @return 0 on success, negative on failure.
  int zd_config_default(ffi.Pointer<ffi.Opaque> config) {
    return _zd_config_default(config);
  }

  late final _zd_config_defaultPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Opaque>)>>(
        'zd_config_default',
      );
  late final _zd_config_default = _zd_config_defaultPtr
      .asFunction<int Function(ffi.Pointer<ffi.Opaque>)>();

  /// Inserts a JSON5 value into the configuration at the given key path.
  ///
  /// Takes a mutable owned config pointer. Internally obtains a mutable loan
  /// via z_config_loan_mut() before calling zc_config_insert_json5().
  ///
  /// @param config  Pointer to a valid z_owned_config_t.
  /// @param key     Configuration key path (e.g., "mode").
  /// @param value   JSON5 value string (e.g., "\"peer\"").
  /// @return 0 on success, negative on failure.
  int zd_config_insert_json5(
    ffi.Pointer<ffi.Opaque> config,
    ffi.Pointer<ffi.Char> key,
    ffi.Pointer<ffi.Char> value,
  ) {
    return _zd_config_insert_json5(config, key, value);
  }

  late final _zd_config_insert_json5Ptr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Opaque>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('zd_config_insert_json5');
  late final _zd_config_insert_json5 = _zd_config_insert_json5Ptr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Opaque>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// Obtains a const loaned reference to the configuration.
  ///
  /// @param config  Pointer to a valid z_owned_config_t.
  /// @return Const pointer to the loaned config.
  ffi.Pointer<ffi.Opaque> zd_config_loan(ffi.Pointer<ffi.Opaque> config) {
    return _zd_config_loan(config);
  }

  late final _zd_config_loanPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Opaque> Function(ffi.Pointer<ffi.Opaque>)
        >
      >('zd_config_loan');
  late final _zd_config_loan = _zd_config_loanPtr
      .asFunction<ffi.Pointer<ffi.Opaque> Function(ffi.Pointer<ffi.Opaque>)>();

  /// Drops (frees) the configuration.
  ///
  /// After this call the owned config is in gravestone state.
  /// A second drop is a safe no-op.
  ///
  /// @param config  Pointer to a z_owned_config_t to drop.
  void zd_config_drop(ffi.Pointer<ffi.Opaque> config) {
    return _zd_config_drop(config);
  }

  late final _zd_config_dropPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Opaque>)>>(
        'zd_config_drop',
      );
  late final _zd_config_drop = _zd_config_dropPtr
      .asFunction<void Function(ffi.Pointer<ffi.Opaque>)>();

  /// Returns the size of z_owned_session_t in bytes.
  ///
  /// Used by Dart to allocate the correct amount of native memory
  /// for opaque zenoh types.
  int zd_session_sizeof() {
    return _zd_session_sizeof();
  }

  late final _zd_session_sizeofPtr =
      _lookup<ffi.NativeFunction<ffi.Size Function()>>('zd_session_sizeof');
  late final _zd_session_sizeof = _zd_session_sizeofPtr
      .asFunction<int Function()>();

  /// Opens a Zenoh session with the given configuration.
  ///
  /// @param session  Pointer to an uninitialized z_owned_session_t.
  /// @param config   Pointer to a z_owned_config_t (consumed by z_open).
  /// @return 0 on success, negative on failure.
  int zd_open_session(
    ffi.Pointer<ffi.Opaque> session,
    ffi.Pointer<ffi.Opaque> config,
  ) {
    return _zd_open_session(session, config);
  }

  late final _zd_open_sessionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>)
        >
      >('zd_open_session');
  late final _zd_open_session = _zd_open_sessionPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>)
      >();

  /// Obtains a const loaned reference to the session.
  ///
  /// @param session  Pointer to a valid z_owned_session_t.
  /// @return Const pointer to the loaned session.
  ffi.Pointer<ffi.Opaque> zd_session_loan(ffi.Pointer<ffi.Opaque> session) {
    return _zd_session_loan(session);
  }

  late final _zd_session_loanPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Opaque> Function(ffi.Pointer<ffi.Opaque>)
        >
      >('zd_session_loan');
  late final _zd_session_loan = _zd_session_loanPtr
      .asFunction<ffi.Pointer<ffi.Opaque> Function(ffi.Pointer<ffi.Opaque>)>();

  /// Gracefully closes and drops the session.
  ///
  /// Calls z_close for graceful shutdown, then z_session_drop to release
  /// resources. After this call the owned session is in gravestone state.
  ///
  /// @param session  Pointer to a z_owned_session_t to close and drop.
  void zd_close_session(ffi.Pointer<ffi.Opaque> session) {
    return _zd_close_session(session);
  }

  late final _zd_close_sessionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Opaque>)>>(
        'zd_close_session',
      );
  late final _zd_close_session = _zd_close_sessionPtr
      .asFunction<void Function(ffi.Pointer<ffi.Opaque>)>();

  /// Returns the size of z_view_keyexpr_t in bytes.
  ///
  /// Used by Dart to allocate the correct amount of native memory
  /// for opaque zenoh types.
  int zd_view_keyexpr_sizeof() {
    return _zd_view_keyexpr_sizeof();
  }

  late final _zd_view_keyexpr_sizeofPtr =
      _lookup<ffi.NativeFunction<ffi.Size Function()>>(
        'zd_view_keyexpr_sizeof',
      );
  late final _zd_view_keyexpr_sizeof = _zd_view_keyexpr_sizeofPtr
      .asFunction<int Function()>();

  /// Creates a view key expression from a null-terminated string.
  ///
  /// The string must remain valid for the lifetime of the view.
  ///
  /// @param ke    Pointer to an uninitialized z_view_keyexpr_t.
  /// @param expr  Null-terminated key expression string.
  /// @return 0 on success, Z_EINVAL (-1) if the expression is invalid.
  int zd_view_keyexpr_from_str(
    ffi.Pointer<ffi.Opaque> ke,
    ffi.Pointer<ffi.Char> expr,
  ) {
    return _zd_view_keyexpr_from_str(ke, expr);
  }

  late final _zd_view_keyexpr_from_strPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Char>)
        >
      >('zd_view_keyexpr_from_str');
  late final _zd_view_keyexpr_from_str = _zd_view_keyexpr_from_strPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Char>)
      >();

  /// Obtains a const loaned reference to the key expression.
  ///
  /// @param ke  Pointer to a valid z_view_keyexpr_t.
  /// @return Const pointer to the loaned key expression.
  ffi.Pointer<ffi.Opaque> zd_view_keyexpr_loan(ffi.Pointer<ffi.Opaque> ke) {
    return _zd_view_keyexpr_loan(ke);
  }

  late final _zd_view_keyexpr_loanPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Opaque> Function(ffi.Pointer<ffi.Opaque>)
        >
      >('zd_view_keyexpr_loan');
  late final _zd_view_keyexpr_loan = _zd_view_keyexpr_loanPtr
      .asFunction<ffi.Pointer<ffi.Opaque> Function(ffi.Pointer<ffi.Opaque>)>();

  /// Converts a loaned key expression to a view string.
  ///
  /// The output view string borrows from the key expression and must not
  /// outlive it. Returns void -- always succeeds on a valid loaned keyexpr.
  ///
  /// @param ke   Const pointer to a loaned key expression.
  /// @param out  Pointer to an uninitialized z_view_string_t to receive the result.
  void zd_keyexpr_as_view_string(
    ffi.Pointer<ffi.Opaque> ke,
    ffi.Pointer<ffi.Opaque> out,
  ) {
    return _zd_keyexpr_as_view_string(ke, out);
  }

  late final _zd_keyexpr_as_view_stringPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>)
        >
      >('zd_keyexpr_as_view_string');
  late final _zd_keyexpr_as_view_string = _zd_keyexpr_as_view_stringPtr
      .asFunction<
        void Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>)
      >();

  /// Returns the size of z_owned_bytes_t in bytes.
  ///
  /// Used by Dart to allocate the correct amount of native memory
  /// for opaque zenoh types.
  int zd_bytes_sizeof() {
    return _zd_bytes_sizeof();
  }

  late final _zd_bytes_sizeofPtr =
      _lookup<ffi.NativeFunction<ffi.Size Function()>>('zd_bytes_sizeof');
  late final _zd_bytes_sizeof = _zd_bytes_sizeofPtr
      .asFunction<int Function()>();

  /// Copies a null-terminated string into owned bytes.
  ///
  /// @param bytes  Pointer to an uninitialized z_owned_bytes_t.
  /// @param str    Null-terminated string to copy.
  /// @return 0 on success, negative on failure.
  int zd_bytes_copy_from_str(
    ffi.Pointer<ffi.Opaque> bytes,
    ffi.Pointer<ffi.Char> str,
  ) {
    return _zd_bytes_copy_from_str(bytes, str);
  }

  late final _zd_bytes_copy_from_strPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Char>)
        >
      >('zd_bytes_copy_from_str');
  late final _zd_bytes_copy_from_str = _zd_bytes_copy_from_strPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Char>)
      >();

  /// Copies a buffer into owned bytes.
  ///
  /// @param bytes  Pointer to an uninitialized z_owned_bytes_t.
  /// @param data   Pointer to the buffer data.
  /// @param len    Length of the buffer in bytes.
  /// @return 0 on success, negative on failure.
  int zd_bytes_copy_from_buf(
    ffi.Pointer<ffi.Opaque> bytes,
    ffi.Pointer<ffi.Uint8> data,
    int len,
  ) {
    return _zd_bytes_copy_from_buf(bytes, data, len);
  }

  late final _zd_bytes_copy_from_bufPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Opaque>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
          )
        >
      >('zd_bytes_copy_from_buf');
  late final _zd_bytes_copy_from_buf = _zd_bytes_copy_from_bufPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Uint8>, int)
      >();

  /// Converts loaned bytes to an owned string.
  ///
  /// @param bytes  Const pointer to a loaned bytes reference.
  /// @param out    Pointer to an uninitialized z_owned_string_t to receive the result.
  /// @return 0 on success, negative on failure.
  int zd_bytes_to_string(
    ffi.Pointer<ffi.Opaque> bytes,
    ffi.Pointer<ffi.Opaque> out,
  ) {
    return _zd_bytes_to_string(bytes, out);
  }

  late final _zd_bytes_to_stringPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>)
        >
      >('zd_bytes_to_string');
  late final _zd_bytes_to_string = _zd_bytes_to_stringPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>)
      >();

  /// Obtains a const loaned reference to the bytes.
  ///
  /// @param bytes  Pointer to a valid z_owned_bytes_t.
  /// @return Const pointer to the loaned bytes.
  ffi.Pointer<ffi.Opaque> zd_bytes_loan(ffi.Pointer<ffi.Opaque> bytes) {
    return _zd_bytes_loan(bytes);
  }

  late final _zd_bytes_loanPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Opaque> Function(ffi.Pointer<ffi.Opaque>)
        >
      >('zd_bytes_loan');
  late final _zd_bytes_loan = _zd_bytes_loanPtr
      .asFunction<ffi.Pointer<ffi.Opaque> Function(ffi.Pointer<ffi.Opaque>)>();

  /// Drops (frees) owned bytes.
  ///
  /// After this call the owned bytes are in gravestone state.
  /// A second drop is a safe no-op.
  ///
  /// @param bytes  Pointer to a z_owned_bytes_t to drop.
  void zd_bytes_drop(ffi.Pointer<ffi.Opaque> bytes) {
    return _zd_bytes_drop(bytes);
  }

  late final _zd_bytes_dropPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Opaque>)>>(
        'zd_bytes_drop',
      );
  late final _zd_bytes_drop = _zd_bytes_dropPtr
      .asFunction<void Function(ffi.Pointer<ffi.Opaque>)>();

  /// Returns the size of z_owned_string_t in bytes.
  ///
  /// Used by Dart to allocate the correct amount of native memory
  /// for opaque zenoh types.
  int zd_string_sizeof() {
    return _zd_string_sizeof();
  }

  late final _zd_string_sizeofPtr =
      _lookup<ffi.NativeFunction<ffi.Size Function()>>('zd_string_sizeof');
  late final _zd_string_sizeof = _zd_string_sizeofPtr
      .asFunction<int Function()>();

  /// Obtains a const loaned reference to the owned string.
  ///
  /// @param str  Pointer to a valid z_owned_string_t.
  /// @return Const pointer to the loaned string.
  ffi.Pointer<ffi.Opaque> zd_string_loan(ffi.Pointer<ffi.Opaque> str) {
    return _zd_string_loan(str);
  }

  late final _zd_string_loanPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Opaque> Function(ffi.Pointer<ffi.Opaque>)
        >
      >('zd_string_loan');
  late final _zd_string_loan = _zd_string_loanPtr
      .asFunction<ffi.Pointer<ffi.Opaque> Function(ffi.Pointer<ffi.Opaque>)>();

  /// Returns a pointer to the data of a loaned string.
  ///
  /// The returned pointer is NOT guaranteed to be null-terminated.
  ///
  /// @param str  Const pointer to a loaned string.
  /// @return Pointer to the string data.
  ffi.Pointer<ffi.Char> zd_string_data(ffi.Pointer<ffi.Opaque> str) {
    return _zd_string_data(str);
  }

  late final _zd_string_dataPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Opaque>)
        >
      >('zd_string_data');
  late final _zd_string_data = _zd_string_dataPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Opaque>)>();

  /// Returns the length of a loaned string (in bytes, NOT including any terminator).
  ///
  /// @param str  Const pointer to a loaned string.
  /// @return Length of the string data in bytes.
  int zd_string_len(ffi.Pointer<ffi.Opaque> str) {
    return _zd_string_len(str);
  }

  late final _zd_string_lenPtr =
      _lookup<ffi.NativeFunction<ffi.Size Function(ffi.Pointer<ffi.Opaque>)>>(
        'zd_string_len',
      );
  late final _zd_string_len = _zd_string_lenPtr
      .asFunction<int Function(ffi.Pointer<ffi.Opaque>)>();

  /// Drops (frees) an owned string.
  ///
  /// After this call the owned string is in gravestone state.
  /// A second drop is a safe no-op.
  ///
  /// @param str  Pointer to a z_owned_string_t to drop.
  void zd_string_drop(ffi.Pointer<ffi.Opaque> str) {
    return _zd_string_drop(str);
  }

  late final _zd_string_dropPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Opaque>)>>(
        'zd_string_drop',
      );
  late final _zd_string_drop = _zd_string_dropPtr
      .asFunction<void Function(ffi.Pointer<ffi.Opaque>)>();

  /// Returns the size of z_view_string_t in bytes.
  ///
  /// Used by Dart to allocate the correct amount of native memory
  /// for opaque zenoh types.
  int zd_view_string_sizeof() {
    return _zd_view_string_sizeof();
  }

  late final _zd_view_string_sizeofPtr =
      _lookup<ffi.NativeFunction<ffi.Size Function()>>('zd_view_string_sizeof');
  late final _zd_view_string_sizeof = _zd_view_string_sizeofPtr
      .asFunction<int Function()>();

  /// Returns a pointer to the data of a view string.
  ///
  /// Internally loans the view string and calls z_string_data on the loaned ref.
  /// The returned pointer is NOT guaranteed to be null-terminated.
  ///
  /// @param str  Pointer to a valid z_view_string_t.
  /// @return Pointer to the string data.
  ffi.Pointer<ffi.Char> zd_view_string_data(ffi.Pointer<ffi.Opaque> str) {
    return _zd_view_string_data(str);
  }

  late final _zd_view_string_dataPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Opaque>)
        >
      >('zd_view_string_data');
  late final _zd_view_string_data = _zd_view_string_dataPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Opaque>)>();

  /// Returns the length of a view string (in bytes, NOT including any terminator).
  ///
  /// Internally loans the view string and calls z_string_len on the loaned ref.
  ///
  /// @param str  Pointer to a valid z_view_string_t.
  /// @return Length of the string data in bytes.
  int zd_view_string_len(ffi.Pointer<ffi.Opaque> str) {
    return _zd_view_string_len(str);
  }

  late final _zd_view_string_lenPtr =
      _lookup<ffi.NativeFunction<ffi.Size Function(ffi.Pointer<ffi.Opaque>)>>(
        'zd_view_string_len',
      );
  late final _zd_view_string_len = _zd_view_string_lenPtr
      .asFunction<int Function(ffi.Pointer<ffi.Opaque>)>();

  /// Publishes data on the given key expression.
  ///
  /// The payload is consumed (moved) by this call -- the caller must not
  /// use the owned bytes after calling zd_put.
  ///
  /// @param session  Const pointer to a loaned session.
  /// @param keyexpr  Const pointer to a loaned key expression.
  /// @param payload  Pointer to an owned bytes (consumed via z_bytes_move).
  /// @return 0 on success, negative on failure.
  int zd_put(
    ffi.Pointer<ffi.Opaque> session,
    ffi.Pointer<ffi.Opaque> keyexpr,
    ffi.Pointer<ffi.Opaque> payload,
  ) {
    return _zd_put(session, keyexpr, payload);
  }

  late final _zd_putPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Opaque>,
            ffi.Pointer<ffi.Opaque>,
            ffi.Pointer<ffi.Opaque>,
          )
        >
      >('zd_put');
  late final _zd_put = _zd_putPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Opaque>,
          ffi.Pointer<ffi.Opaque>,
          ffi.Pointer<ffi.Opaque>,
        )
      >();

  /// Deletes a resource on the given key expression.
  ///
  /// @param session  Const pointer to a loaned session.
  /// @param keyexpr  Const pointer to a loaned key expression.
  /// @return 0 on success, negative on failure.
  int zd_delete(
    ffi.Pointer<ffi.Opaque> session,
    ffi.Pointer<ffi.Opaque> keyexpr,
  ) {
    return _zd_delete(session, keyexpr);
  }

  late final _zd_deletePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>)
        >
      >('zd_delete');
  late final _zd_delete = _zd_deletePtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>)
      >();

  /// Returns the size of z_owned_subscriber_t in bytes.
  ///
  /// Used by Dart to allocate the correct amount of native memory
  /// for opaque zenoh types.
  int zd_subscriber_sizeof() {
    return _zd_subscriber_sizeof();
  }

  late final _zd_subscriber_sizeofPtr =
      _lookup<ffi.NativeFunction<ffi.Size Function()>>('zd_subscriber_sizeof');
  late final _zd_subscriber_sizeof = _zd_subscriber_sizeofPtr
      .asFunction<int Function()>();

  /// Declares a subscriber on the given key expression.
  ///
  /// Samples are posted to the Dart isolate via `Dart_PostCObject_DL` on
  /// the given native port. Each sample is sent as a `Dart_CObject` array
  /// of 4 elements: [keyexpr(string), payload(Uint8List), kind(int64),
  /// attachment(null or Uint8List)].
  ///
  /// @param session     Const pointer to a loaned session.
  /// @param subscriber  Pointer to an uninitialized z_owned_subscriber_t.
  /// @param keyexpr     Const pointer to a loaned key expression.
  /// @param dart_port   The Dart native port to post samples to.
  /// @return 0 on success, negative on failure.
  int zd_declare_subscriber(
    ffi.Pointer<ffi.Opaque> session,
    ffi.Pointer<ffi.Opaque> subscriber,
    ffi.Pointer<ffi.Opaque> keyexpr,
    int dart_port,
  ) {
    return _zd_declare_subscriber(session, subscriber, keyexpr, dart_port);
  }

  late final _zd_declare_subscriberPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Opaque>,
            ffi.Pointer<ffi.Opaque>,
            ffi.Pointer<ffi.Opaque>,
            ffi.Int64,
          )
        >
      >('zd_declare_subscriber');
  late final _zd_declare_subscriber = _zd_declare_subscriberPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Opaque>,
          ffi.Pointer<ffi.Opaque>,
          ffi.Pointer<ffi.Opaque>,
          int,
        )
      >();

  /// Drops (undeclares and frees) a subscriber.
  ///
  /// After this call the owned subscriber is in gravestone state.
  /// A second drop is a safe no-op.
  ///
  /// @param subscriber  Pointer to a z_owned_subscriber_t to drop.
  void zd_subscriber_drop(ffi.Pointer<ffi.Opaque> subscriber) {
    return _zd_subscriber_drop(subscriber);
  }

  late final _zd_subscriber_dropPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Opaque>)>>(
        'zd_subscriber_drop',
      );
  late final _zd_subscriber_drop = _zd_subscriber_dropPtr
      .asFunction<void Function(ffi.Pointer<ffi.Opaque>)>();

  /// Returns the size of z_owned_publisher_t in bytes.
  int zd_publisher_sizeof() {
    return _zd_publisher_sizeof();
  }

  late final _zd_publisher_sizeofPtr =
      _lookup<ffi.NativeFunction<ffi.Size Function()>>('zd_publisher_sizeof');
  late final _zd_publisher_sizeof = _zd_publisher_sizeofPtr
      .asFunction<int Function()>();

  /// Declares a publisher on the given key expression.
  ///
  /// @param session             Const pointer to a loaned session.
  /// @param publisher           Pointer to an uninitialized z_owned_publisher_t.
  /// @param keyexpr             Const pointer to a loaned key expression.
  /// @param encoding            MIME type string for default encoding (NULL = default).
  /// @param congestion_control  Congestion control strategy (-1 = default/block).
  /// @param priority            Message priority (-1 = default/data=5).
  /// @return 0 on success, negative on failure.
  int zd_declare_publisher(
    ffi.Pointer<ffi.Opaque> session,
    ffi.Pointer<ffi.Opaque> publisher,
    ffi.Pointer<ffi.Opaque> keyexpr,
    ffi.Pointer<ffi.Char> encoding,
    int congestion_control,
    int priority,
  ) {
    return _zd_declare_publisher(
      session,
      publisher,
      keyexpr,
      encoding,
      congestion_control,
      priority,
    );
  }

  late final _zd_declare_publisherPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Opaque>,
            ffi.Pointer<ffi.Opaque>,
            ffi.Pointer<ffi.Opaque>,
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Int,
          )
        >
      >('zd_declare_publisher');
  late final _zd_declare_publisher = _zd_declare_publisherPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Opaque>,
          ffi.Pointer<ffi.Opaque>,
          ffi.Pointer<ffi.Opaque>,
          ffi.Pointer<ffi.Char>,
          int,
          int,
        )
      >();

  /// Obtains a const loaned reference to the publisher.
  ffi.Pointer<ffi.Opaque> zd_publisher_loan(ffi.Pointer<ffi.Opaque> publisher) {
    return _zd_publisher_loan(publisher);
  }

  late final _zd_publisher_loanPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Opaque> Function(ffi.Pointer<ffi.Opaque>)
        >
      >('zd_publisher_loan');
  late final _zd_publisher_loan = _zd_publisher_loanPtr
      .asFunction<ffi.Pointer<ffi.Opaque> Function(ffi.Pointer<ffi.Opaque>)>();

  /// Drops (undeclares and frees) a publisher.
  void zd_publisher_drop(ffi.Pointer<ffi.Opaque> publisher) {
    return _zd_publisher_drop(publisher);
  }

  late final _zd_publisher_dropPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Opaque>)>>(
        'zd_publisher_drop',
      );
  late final _zd_publisher_drop = _zd_publisher_dropPtr
      .asFunction<void Function(ffi.Pointer<ffi.Opaque>)>();

  /// Publishes data through the publisher.
  ///
  /// @param publisher   Const pointer to a loaned publisher.
  /// @param payload     Pointer to owned bytes (consumed via z_bytes_move).
  /// @param encoding    MIME type string for per-put encoding override (NULL = publisher default).
  /// @param attachment  Pointer to owned bytes for attachment (consumed if non-NULL, NULL = no attachment).
  /// @return 0 on success, negative on failure.
  int zd_publisher_put(
    ffi.Pointer<ffi.Opaque> publisher,
    ffi.Pointer<ffi.Opaque> payload,
    ffi.Pointer<ffi.Char> encoding,
    ffi.Pointer<ffi.Opaque> attachment,
  ) {
    return _zd_publisher_put(publisher, payload, encoding, attachment);
  }

  late final _zd_publisher_putPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Opaque>,
            ffi.Pointer<ffi.Opaque>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Opaque>,
          )
        >
      >('zd_publisher_put');
  late final _zd_publisher_put = _zd_publisher_putPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Opaque>,
          ffi.Pointer<ffi.Opaque>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Opaque>,
        )
      >();

  /// Sends a DELETE through the publisher.
  int zd_publisher_delete(ffi.Pointer<ffi.Opaque> publisher) {
    return _zd_publisher_delete(publisher);
  }

  late final _zd_publisher_deletePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Opaque>)>>(
        'zd_publisher_delete',
      );
  late final _zd_publisher_delete = _zd_publisher_deletePtr
      .asFunction<int Function(ffi.Pointer<ffi.Opaque>)>();

  /// Returns the key expression of a publisher.
  ffi.Pointer<ffi.Opaque> zd_publisher_keyexpr(
    ffi.Pointer<ffi.Opaque> publisher,
  ) {
    return _zd_publisher_keyexpr(publisher);
  }

  late final _zd_publisher_keyexprPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Opaque> Function(ffi.Pointer<ffi.Opaque>)
        >
      >('zd_publisher_keyexpr');
  late final _zd_publisher_keyexpr = _zd_publisher_keyexprPtr
      .asFunction<ffi.Pointer<ffi.Opaque> Function(ffi.Pointer<ffi.Opaque>)>();

  /// Declares a background matching listener on the publisher.
  ///
  /// Matching status changes are posted to the Dart isolate via the given
  /// native port as Int64 values (1 = matching, 0 = not matching).
  ///
  /// @param publisher  Const pointer to a loaned publisher.
  /// @param dart_port  The Dart native port to post matching status to.
  /// @return 0 on success, negative on failure.
  int zd_publisher_declare_background_matching_listener(
    ffi.Pointer<ffi.Opaque> publisher,
    int dart_port,
  ) {
    return _zd_publisher_declare_background_matching_listener(
      publisher,
      dart_port,
    );
  }

  late final _zd_publisher_declare_background_matching_listenerPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Opaque>, ffi.Int64)>
      >('zd_publisher_declare_background_matching_listener');
  late final _zd_publisher_declare_background_matching_listener =
      _zd_publisher_declare_background_matching_listenerPtr
          .asFunction<int Function(ffi.Pointer<ffi.Opaque>, int)>();

  /// Gets the current matching status of a publisher.
  ///
  /// @param publisher  Const pointer to a loaned publisher.
  /// @param matching   Out parameter: filled with 0 (no match) or 1 (match).
  /// @return 0 on success, negative on failure.
  int zd_publisher_get_matching_status(
    ffi.Pointer<ffi.Opaque> publisher,
    ffi.Pointer<ffi.Int> matching,
  ) {
    return _zd_publisher_get_matching_status(publisher, matching);
  }

  late final _zd_publisher_get_matching_statusPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Int>)
        >
      >('zd_publisher_get_matching_status');
  late final _zd_publisher_get_matching_status =
      _zd_publisher_get_matching_statusPtr
          .asFunction<
            int Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Int>)
          >();
}

final class UnnamedStruct extends ffi.Struct {
  @ffi.UnsignedInt()
  external int __low;

  @ffi.UnsignedInt()
  external int __high;
}

final class __atomic_wide_counter extends ffi.Union {
  @ffi.UnsignedLongLong()
  external int __value64;

  external UnnamedStruct __value32;
}

final class __pthread_internal_list extends ffi.Struct {
  external ffi.Pointer<__pthread_internal_list> __prev;

  external ffi.Pointer<__pthread_internal_list> __next;
}

final class __pthread_mutex_s extends ffi.Struct {
  @ffi.Int()
  external int __lock;

  @ffi.UnsignedInt()
  external int __count;

  @ffi.Int()
  external int __owner;

  @ffi.UnsignedInt()
  external int __nusers;

  @ffi.Int()
  external int __kind;

  @ffi.Short()
  external int __spins;

  @ffi.Short()
  external int __elision;

  external __pthread_internal_list __list;
}

final class __pthread_rwlock_arch_t extends ffi.Struct {
  @ffi.UnsignedInt()
  external int __readers;

  @ffi.UnsignedInt()
  external int __writers;

  @ffi.UnsignedInt()
  external int __wrphase_futex;

  @ffi.UnsignedInt()
  external int __writers_futex;

  @ffi.UnsignedInt()
  external int __pad3;

  @ffi.UnsignedInt()
  external int __pad4;

  @ffi.Int()
  external int __cur_writer;

  @ffi.Int()
  external int __shared;

  @ffi.SignedChar()
  external int __rwelision;

  @ffi.Array.multi([7])
  external ffi.Array<ffi.UnsignedChar> __pad1;

  @ffi.UnsignedLong()
  external int __pad2;

  @ffi.UnsignedInt()
  external int __flags;
}

final class __pthread_cond_s extends ffi.Struct {
  external __atomic_wide_counter __wseq;

  external __atomic_wide_counter __g1_start;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.UnsignedInt> __g_refs;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.UnsignedInt> __g_size;

  @ffi.UnsignedInt()
  external int __g1_orig_size;

  @ffi.UnsignedInt()
  external int __wrefs;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.UnsignedInt> __g_signals;
}

final class pthread_mutexattr_t extends ffi.Union {
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Char> __size;

  @ffi.Int()
  external int __align;
}

final class pthread_condattr_t extends ffi.Union {
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Char> __size;

  @ffi.Int()
  external int __align;
}

final class pthread_attr_t extends ffi.Union {
  @ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_mutex_t extends ffi.Union {
  external __pthread_mutex_s __data;

  @ffi.Array.multi([40])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_cond_t extends ffi.Union {
  external __pthread_cond_s __data;

  @ffi.Array.multi([48])
  external ffi.Array<ffi.Char> __size;

  @ffi.LongLong()
  external int __align;
}

final class pthread_rwlock_t extends ffi.Union {
  external __pthread_rwlock_arch_t __data;

  @ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_rwlockattr_t extends ffi.Union {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_barrier_t extends ffi.Union {
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_barrierattr_t extends ffi.Union {
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Char> __size;

  @ffi.Int()
  external int __align;
}

/// A loaned Zenoh data.
final class z_loaned_bytes_t extends ffi.Struct {
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Uint8> _0;
}

/// A Zenoh data.
///
/// To minimize copies and reallocations, Zenoh may provide data in several separate buffers.
final class z_owned_bytes_t extends ffi.Struct {
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Uint8> _0;
}

/// A loaned sequence of bytes.
final class z_loaned_slice_t extends ffi.Struct {
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Uint8> _0;
}

/// A loaned string.
final class z_loaned_string_t extends ffi.Struct {
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Uint8> _0;
}

final class z_owned_slice_t extends ffi.Struct {
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Uint8> _0;
}

/// The wrapper type for strings allocated by Zenoh.
final class z_owned_string_t extends ffi.Struct {
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Uint8> _0;
}

/// A contiguous sequence of bytes owned by some other entity.
final class z_view_slice_t extends ffi.Struct {
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Uint8> _0;
}

/// An loaned writer for payload.
final class z_loaned_bytes_writer_t extends ffi.Struct {
  @ffi.Array.multi([56])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned writer for payload.
final class z_owned_bytes_writer_t extends ffi.Struct {
  @ffi.Array.multi([56])
  external ffi.Array<ffi.Uint8> _0;
}

/// A loaned Zenoh session.
final class z_loaned_session_t extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> _0;
}

/// A loaned hello message.
final class z_loaned_hello_t extends ffi.Struct {
  @ffi.Array.multi([48])
  external ffi.Array<ffi.Uint8> _0;
}

/// Loaned closure.
final class z_loaned_closure_hello_t extends ffi.Struct {
  @ffi.Size()
  external int _0;

  @ffi.Size()
  external int _1;

  @ffi.Size()
  external int _2;
}

/// A loaned Zenoh query.
final class z_loaned_query_t extends ffi.Struct {
  @ffi.Array.multi([136])
  external ffi.Array<ffi.Uint8> _0;
}

/// Loaned closure.
final class z_loaned_closure_query_t extends ffi.Struct {
  @ffi.Size()
  external int _0;

  @ffi.Size()
  external int _1;

  @ffi.Size()
  external int _2;
}

/// A loaned reply.
final class z_loaned_reply_t extends ffi.Struct {
  @ffi.Array.multi([184])
  external ffi.Array<ffi.Uint8> _0;
}

/// Loaned closure.
final class z_loaned_closure_reply_t extends ffi.Struct {
  @ffi.Size()
  external int _0;

  @ffi.Size()
  external int _1;

  @ffi.Size()
  external int _2;
}

/// A loaned Zenoh sample.
final class z_loaned_sample_t extends ffi.Struct {
  @ffi.Array.multi([184])
  external ffi.Array<ffi.Uint8> _0;
}

/// Loaned closure.
final class z_loaned_closure_sample_t extends ffi.Struct {
  @ffi.Size()
  external int _0;

  @ffi.Size()
  external int _1;

  @ffi.Size()
  external int _2;
}

/// @brief A Zenoh ID.
///
/// In general, valid Zenoh IDs are LSB-first 128bit unsigned and non-zero integers.
final class z_id_t extends ffi.Struct {
  @ffi.Array.multi([16])
  external ffi.Array<ffi.Uint8> id;
}

/// @brief Loaned closure.
final class z_loaned_closure_zid_t extends ffi.Struct {
  @ffi.Size()
  external int _0;

  @ffi.Size()
  external int _1;

  @ffi.Size()
  external int _2;
}

/// An owned conditional variable.
///
/// Used in combination with `z_owned_mutex_t` to wake up thread when certain conditions are met.
final class z_owned_condvar_t extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> _0;
}

/// A loaned conditional variable.
final class z_loaned_condvar_t extends ffi.Struct {
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Uint8> _0;
}

/// A loaned mutex.
final class z_loaned_mutex_t extends ffi.Struct {
  @ffi.Array.multi([24])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned Zenoh configuration.
final class z_owned_config_t extends ffi.Struct {
  @ffi.Array.multi([2008])
  external ffi.Array<ffi.Uint8> _0;
}

/// A loaned Zenoh configuration.
final class z_loaned_config_t extends ffi.Struct {
  @ffi.Array.multi([2008])
  external ffi.Array<ffi.Uint8> _0;
}

/// A loaned key expression.
///
/// Key expressions can identify a single key or a set of keys.
///
/// Examples :
/// - ``"key/expression"``.
/// - ``"key/ex*"``.
///
/// Using `z_declare_keyexpr` allows Zenoh to optimize a key expression,
/// both for local processing and network-wise.
final class z_loaned_keyexpr_t extends ffi.Struct {
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Uint8> _0;
}

/// A Zenoh-allocated <a href="https://zenoh.io/docs/manual/abstractions/#key-expression"> key expression </a>.
///
/// Key expressions can identify a single key or a set of keys.
///
/// Examples :
/// - ``"key/expression"``.
/// - ``"key/ex*"``.
///
/// Key expressions can be mapped to numerical ids through `z_declare_keyexpr`
/// for wire and computation efficiency.
///
/// Internally key expressiobn can be either:
/// - A plain string expression.
/// - A pure numerical id.
/// - The combination of a numerical prefix and a string suffix.
final class z_owned_keyexpr_t extends ffi.Struct {
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned Zenoh <a href="https://zenoh.io/docs/manual/abstractions/#publisher"> publisher </a>.
final class z_owned_publisher_t extends ffi.Struct {
  @ffi.Array.multi([104])
  external ffi.Array<ffi.Uint8> _0;
}

/// The <a href="https://zenoh.io/docs/manual/abstractions/#encoding"> encoding </a> of Zenoh data.
final class z_owned_encoding_t extends ffi.Struct {
  @ffi.Array.multi([40])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned Zenoh <a href="https://zenoh.io/docs/manual/abstractions/#queryable"> queryable </a>.
///
/// Responds to queries sent via `z_get()` with intersecting key expression.
final class z_owned_queryable_t extends ffi.Struct {
  @ffi.Array.multi([48])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned Zenoh <a href="https://zenoh.io/docs/manual/abstractions/#subscriber"> subscriber </a>.
///
/// Receives data from publication on intersecting key expressions.
/// Destroying the subscriber cancels the subscription.
final class z_owned_subscriber_t extends ffi.Struct {
  @ffi.Array.multi([48])
  external ffi.Array<ffi.Uint8> _0;
}

/// A loaned Zenoh encoding.
final class z_loaned_encoding_t extends ffi.Struct {
  @ffi.Array.multi([40])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned Zenoh fifo query handler.
final class z_owned_fifo_handler_query_t extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned Zenoh fifo reply handler.
final class z_owned_fifo_handler_reply_t extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned Zenoh fifo sample handler.
final class z_owned_fifo_handler_sample_t extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> _0;
}

/// An loaned Zenoh fifo query handler.
final class z_loaned_fifo_handler_query_t extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned Zenoh query received by a queryable.
///
/// Queries are atomically reference-counted, letting you extract them from the callback that handed them to you by cloning.
final class z_owned_query_t extends ffi.Struct {
  @ffi.Array.multi([136])
  external ffi.Array<ffi.Uint8> _0;
}

/// An loaned Zenoh fifo reply handler.
final class z_loaned_fifo_handler_reply_t extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned reply from a Queryable to a `z_get()`.
final class z_owned_reply_t extends ffi.Struct {
  @ffi.Array.multi([184])
  external ffi.Array<ffi.Uint8> _0;
}

/// An loaned Zenoh fifo sample handler.
final class z_loaned_fifo_handler_sample_t extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned Zenoh sample.
///
/// This is a read only type that can only be constructed by cloning a `z_loaned_sample_t`.
/// Like all owned types, it should be freed using z_drop or z_sample_drop.
final class z_owned_sample_t extends ffi.Struct {
  @ffi.Array.multi([184])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned Zenoh-allocated hello message returned by a Zenoh entity to a scout message sent with `z_scout()`.
final class z_owned_hello_t extends ffi.Struct {
  @ffi.Array.multi([48])
  external ffi.Array<ffi.Uint8> _0;
}

/// An array of maybe-owned non-null terminated strings.
final class z_owned_string_array_t extends ffi.Struct {
  @ffi.Array.multi([24])
  external ffi.Array<ffi.Uint8> _0;
}

/// @brief A liveliness token that can be used to provide the network with information about connectivity to its
/// declarer: when constructed, a PUT sample will be received by liveliness subscribers on intersecting key
/// expressions.
///
/// A DELETE on the token's key expression will be received by subscribers if the token is destroyed, or if connectivity between the subscriber and the token's creator is lost.
final class z_owned_liveliness_token_t extends ffi.Struct {
  @ffi.Array.multi([16])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned mutex.
final class z_owned_mutex_t extends ffi.Struct {
  @ffi.Array.multi([24])
  external ffi.Array<ffi.Uint8> _0;
}

/// A Zenoh reply error - a combination of reply error payload and its encoding.
final class z_owned_reply_err_t extends ffi.Struct {
  @ffi.Array.multi([72])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned Zenoh ring query handler.
final class z_owned_ring_handler_query_t extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned Zenoh ring reply handler.
final class z_owned_ring_handler_reply_t extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned Zenoh ring sample handler.
final class z_owned_ring_handler_sample_t extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned Zenoh session.
final class z_owned_session_t extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> _0;
}

/// An owned Zenoh task.
final class z_owned_task_t extends ffi.Struct {
  @ffi.Array.multi([24])
  external ffi.Array<ffi.Uint8> _0;
}

/// The view over a string.
final class z_view_string_t extends ffi.Struct {
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Uint8> _0;
}

final class z_loaned_liveliness_token_t extends ffi.Struct {
  @ffi.Array.multi([16])
  external ffi.Array<ffi.Uint8> _0;
}

/// A loaned Zenoh publisher.
final class z_loaned_publisher_t extends ffi.Struct {
  @ffi.Array.multi([104])
  external ffi.Array<ffi.Uint8> _0;
}

/// A loaned Zenoh queryable.
final class z_loaned_queryable_t extends ffi.Struct {
  @ffi.Array.multi([48])
  external ffi.Array<ffi.Uint8> _0;
}

/// A loaned Zenoh reply error.
final class z_loaned_reply_err_t extends ffi.Struct {
  @ffi.Array.multi([72])
  external ffi.Array<ffi.Uint8> _0;
}

/// An loaned Zenoh ring query handler.
final class z_loaned_ring_handler_query_t extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> _0;
}

/// An loaned Zenoh ring reply handler.
final class z_loaned_ring_handler_reply_t extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> _0;
}

/// An loaned Zenoh ring sample handler.
final class z_loaned_ring_handler_sample_t extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> _0;
}

/// A loaned string array.
final class z_loaned_string_array_t extends ffi.Struct {
  @ffi.Array.multi([24])
  external ffi.Array<ffi.Uint8> _0;
}

/// A loaned Zenoh subscriber.
final class z_loaned_subscriber_t extends ffi.Struct {
  @ffi.Array.multi([48])
  external ffi.Array<ffi.Uint8> _0;
}

/// A user allocated string, viewed as a key expression.
final class z_view_keyexpr_t extends ffi.Struct {
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Uint8> _0;
}

final class z_moved_bytes_t extends ffi.Struct {
  external z_owned_bytes_t _this;
}

final class z_moved_slice_t extends ffi.Struct {
  external z_owned_slice_t _this;
}

final class z_moved_string_t extends ffi.Struct {
  external z_owned_string_t _this;
}

final class z_moved_bytes_writer_t extends ffi.Struct {
  external z_owned_bytes_writer_t _this;
}

/// @brief A hello message-processing closure.
///
/// A closure is a structure that contains all the elements for stateful, memory-leak-free callbacks.
final class z_owned_closure_hello_t extends ffi.Struct {
  external ffi.Pointer<ffi.Void> _context;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<z_loaned_hello_t> hello,
        ffi.Pointer<ffi.Void> context,
      )
    >
  >
  _call;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> context)>
  >
  _drop;
}

/// Moved closure.
final class z_moved_closure_hello_t extends ffi.Struct {
  external z_owned_closure_hello_t _this;
}

/// @brief A struct that indicates if there exist Subscribers matching the Publisher's key expression or Queryables matching Querier's key expression and target.
final class z_matching_status_t extends ffi.Struct {
  /// True if there exist matching Zenoh entities, false otherwise.
  @ffi.Bool()
  external bool matching;
}

/// @warning This API has been marked as unstable: it works as advertised, but it may be changed in a future release.
/// @brief A matching status-processing closure.
///
/// A closure is a structure that contains all the elements for stateful, memory-leak-free callbacks.
final class z_owned_closure_matching_status_t extends ffi.Struct {
  external ffi.Pointer<ffi.Void> _context;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<z_matching_status_t> matching_status,
        ffi.Pointer<ffi.Void> context,
      )
    >
  >
  _call;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> context)>
  >
  _drop;
}

/// @warning This API has been marked as unstable: it works as advertised, but it may be changed in a future release.
/// @brief Loaned closure.
final class z_loaned_closure_matching_status_t extends ffi.Struct {
  @ffi.Size()
  external int _0;

  @ffi.Size()
  external int _1;

  @ffi.Size()
  external int _2;
}

/// @warning This API has been marked as unstable: it works as advertised, but it may be changed in a future release.
/// @brief Moved closure.
final class z_moved_closure_matching_status_t extends ffi.Struct {
  external z_owned_closure_matching_status_t _this;
}

/// @brief A query-processing closure.
///
/// A closure is a structure that contains all the elements for stateful, memory-leak-free callbacks.
final class z_owned_closure_query_t extends ffi.Struct {
  external ffi.Pointer<ffi.Void> _context;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<z_loaned_query_t> query,
        ffi.Pointer<ffi.Void> context,
      )
    >
  >
  _call;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> context)>
  >
  _drop;
}

/// Moved closure.
final class z_moved_closure_query_t extends ffi.Struct {
  external z_owned_closure_query_t _this;
}

/// @brief A reply-processing closure.
///
/// A closure is a structure that contains all the elements for stateful, memory-leak-free callbacks.
final class z_owned_closure_reply_t extends ffi.Struct {
  external ffi.Pointer<ffi.Void> _context;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<z_loaned_reply_t> reply,
        ffi.Pointer<ffi.Void> context,
      )
    >
  >
  _call;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> context)>
  >
  _drop;
}

/// Moved closure.
final class z_moved_closure_reply_t extends ffi.Struct {
  external z_owned_closure_reply_t _this;
}

/// @brief A sample-processing closure.
///
/// A closure is a structure that contains all the elements for stateful, memory-leak-free callbacks.
final class z_owned_closure_sample_t extends ffi.Struct {
  external ffi.Pointer<ffi.Void> _context;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<z_loaned_sample_t> sample,
        ffi.Pointer<ffi.Void> context,
      )
    >
  >
  _call;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> context)>
  >
  _drop;
}

/// Moved closure.
final class z_moved_closure_sample_t extends ffi.Struct {
  external z_owned_closure_sample_t _this;
}

/// @brief A zenoh id-processing closure.
///
/// A closure is a structure that contains all the elements for stateful, memory-leak-free callbacks:
final class z_owned_closure_zid_t extends ffi.Struct {
  external ffi.Pointer<ffi.Void> _context;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<z_id_t> z_id, ffi.Pointer<ffi.Void> context)
    >
  >
  _call;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> context)>
  >
  _drop;
}

/// @brief Moved closure.
final class z_moved_closure_zid_t extends ffi.Struct {
  external z_owned_closure_zid_t _this;
}

final class z_moved_condvar_t extends ffi.Struct {
  external z_owned_condvar_t _this;
}

final class z_moved_config_t extends ffi.Struct {
  external z_owned_config_t _this;
}

final class z_moved_encoding_t extends ffi.Struct {
  external z_owned_encoding_t _this;
}

/// An owned Zenoh querier.
///
/// Sends queries to matching queryables.
final class z_owned_querier_t extends ffi.Struct {
  @ffi.Array.multi([80])
  external ffi.Array<ffi.Uint8> _0;
}

final class z_moved_fifo_handler_query_t extends ffi.Struct {
  external z_owned_fifo_handler_query_t _this;
}

final class z_moved_fifo_handler_reply_t extends ffi.Struct {
  external z_owned_fifo_handler_reply_t _this;
}

final class z_moved_fifo_handler_sample_t extends ffi.Struct {
  external z_owned_fifo_handler_sample_t _this;
}

final class z_moved_hello_t extends ffi.Struct {
  external z_owned_hello_t _this;
}

/// @brief An owned Zenoh matching listener.
///
/// A listener that sends notifications when the [`MatchingStatus`] of a publisher or querier changes.
/// Dropping the corresponding publisher, also drops matching listener.
final class z_owned_matching_listener_t extends ffi.Struct {
  @ffi.Array.multi([24])
  external ffi.Array<ffi.Uint8> _0;
}

final class z_moved_keyexpr_t extends ffi.Struct {
  external z_owned_keyexpr_t _this;
}

final class z_moved_liveliness_token_t extends ffi.Struct {
  external z_owned_liveliness_token_t _this;
}

final class z_moved_matching_listener_t extends ffi.Struct {
  external z_owned_matching_listener_t _this;
}

final class z_moved_mutex_t extends ffi.Struct {
  external z_owned_mutex_t _this;
}

final class z_moved_publisher_t extends ffi.Struct {
  external z_owned_publisher_t _this;
}

/// A loaned Zenoh queryable.
final class z_loaned_querier_t extends ffi.Struct {
  @ffi.Array.multi([80])
  external ffi.Array<ffi.Uint8> _0;
}

final class z_moved_querier_t extends ffi.Struct {
  external z_owned_querier_t _this;
}

final class z_moved_query_t extends ffi.Struct {
  external z_owned_query_t _this;
}

final class z_moved_queryable_t extends ffi.Struct {
  external z_owned_queryable_t _this;
}

final class z_moved_reply_t extends ffi.Struct {
  external z_owned_reply_t _this;
}

final class z_moved_reply_err_t extends ffi.Struct {
  external z_owned_reply_err_t _this;
}

final class z_moved_ring_handler_query_t extends ffi.Struct {
  external z_owned_ring_handler_query_t _this;
}

final class z_moved_ring_handler_reply_t extends ffi.Struct {
  external z_owned_ring_handler_reply_t _this;
}

final class z_moved_ring_handler_sample_t extends ffi.Struct {
  external z_owned_ring_handler_sample_t _this;
}

final class z_moved_sample_t extends ffi.Struct {
  external z_owned_sample_t _this;
}

final class z_moved_session_t extends ffi.Struct {
  external z_owned_session_t _this;
}

final class z_moved_string_array_t extends ffi.Struct {
  external z_owned_string_array_t _this;
}

final class z_moved_subscriber_t extends ffi.Struct {
  external z_owned_subscriber_t _this;
}

final class z_moved_task_t extends ffi.Struct {
  external z_owned_task_t _this;
}
